import type { GlossaryTerm } from "./types";

export const glossaryTerms: GlossaryTerm[] = [
  {
    id: "dataset-row",
    zhLabel: "数据行",
    codeLabel: "dataset row",
    definition: "JSONL、Parquet 等输入中的一条记录，尚未经过 Dataset 构造成 Sample 对象。",
    aliases: ["input row"],
    avoid: ["训练样本", "trainer batch"],
    disambiguation: "数据行是外部输入记录；Sample 是框架内协议对象；train data 是转换后的训练侧数据。",
    sourceRefIds: ["dataset.read-file", "dataset.construct-sample"],
    usedBy: ["act-1", "q2"],
  },
  {
    id: "sample-object",
    zhLabel: "Sample 对象",
    codeLabel: "Sample",
    definition: "slime 在 rollout 边界间传递轨迹输入、生成结果、评价与身份信息的 dataclass 实例。",
    aliases: ["Sample instance"],
    avoid: ["样本（不带上下文）", "tensor batch"],
    disambiguation: "中文写作始终使用“Sample 对象/实例”；它不是 dataset row，也不是 Megatron 直接消费的 batch。",
    sourceRefIds: ["sample.dataclass"],
    usedBy: ["act-1", "act-3", "act-4", "act-5", "q2"],
  },
  {
    id: "prompt-group",
    zhLabel: "prompt 组",
    codeLabel: "prompt group",
    definition: "从同一个 prompt 复制并独立生成的一组同组候选，用于组内比较或完整 group 过滤。",
    aliases: ["generation group"],
    avoid: ["rollout sibling", "重复样本"],
    disambiguation: "同一 prompt 的多次生成叫“同组候选”；只有一次逻辑 rollout 拆出的片段才叫 rollout sibling。",
    sourceRefIds: ["rollout.datasource-get-samples"],
    usedBy: ["act-2", "act-4", "q3", "q8"],
  },
  {
    id: "group-index",
    zhLabel: "分组编号",
    codeLabel: "group_index",
    definition: "标记 Sample 属于哪个 prompt group 的身份字段；同组候选拥有相同值。",
    aliases: ["group id"],
    avoid: ["trainer 主键", "rollout_id"],
    disambiguation: "它用于建立组关系，但默认 reward reshape 与 trainer 并不把它当作所有下游的通用主键。",
    sourceRefIds: ["rollout.datasource-get-samples"],
    usedBy: ["act-2", "act-5", "q3"],
  },
  {
    id: "sample-index",
    zhLabel: "Sample 实例编号",
    codeLabel: "index",
    definition: "标记一条物理 Sample 实例的身份；即使属于同一 prompt group，也必须各不相同。",
    aliases: ["sample index"],
    avoid: ["group_index", "rollout_id"],
    disambiguation: "index 区分物理实例；rollout_id 可把多个物理片段重新聚合为一次逻辑执行。",
    sourceRefIds: ["rollout.datasource-get-samples", "rollout.convert-train-data"],
    usedBy: ["act-2", "act-5", "q3", "q8"],
  },
  {
    id: "logical-rollout",
    zhLabel: "逻辑 rollout",
    codeLabel: "logical rollout",
    definition: "训练计数与归一化语义上的一次 rollout 执行；它可能对应一条物理 Sample，也可能 fan-out 为多个片段。",
    aliases: ["logical execution"],
    avoid: ["prompt group", "rollout batch"],
    disambiguation: "prompt group 按输入分组；logical rollout 按一次执行聚合；rollout batch 是一轮收集的集合。",
    sourceRefIds: ["rollout.get-data", "schedule.build-dp-schedule"],
    usedBy: ["act-5", "q8"],
  },
  {
    id: "rollout-id",
    zhLabel: "逻辑 rollout 身份",
    codeLabel: "Sample.rollout_id",
    definition: "把同一次逻辑 rollout 的多个物理训练片段关联起来的 Sample 字段。",
    aliases: ["sample rollout id"],
    avoid: ["训练循环 rollout_id", "group_index", "index"],
    disambiguation: "Sample.rollout_id 描述逻辑执行身份；训练循环 rollout_id 描述外层第几轮收集，两者不是同一个编号。",
    sourceRefIds: ["sample.dataclass", "rollout.convert-train-data"],
    usedBy: ["act-5", "q8"],
  },
  {
    id: "rollout-batch",
    zhLabel: "rollout 批次",
    codeLabel: "rollout batch",
    definition: "训练循环一次收集并准备交给转换与训练侧的一批 rollout 结果。",
    aliases: ["rollout data batch"],
    avoid: ["training step", "prompt group"],
    disambiguation: "一轮 rollout batch 可以再被 scheduler 切成多个 training step。",
    sourceRefIds: ["rollout.manager-generate", "rollout.split-train-data"],
    usedBy: ["act-5"],
  },
  {
    id: "training-step",
    zhLabel: "训练步",
    codeLabel: "training step",
    definition: "按 global batch size 等约束组织、驱动一次训练更新的 logical rollout 集合。",
    aliases: ["optimizer step（在本课简化语境）"],
    avoid: ["microbatch", "rollout batch"],
    disambiguation: "microbatch 是设备与执行调度单位；training step 是优化更新边界；两者数量不必相同。",
    sourceRefIds: ["schedule.build-dp-schedule", "actor.train"],
    usedBy: ["act-5", "act-6", "pre-3"],
  },
  {
    id: "response-length",
    zhLabel: "response 长度",
    codeLabel: "response_length",
    definition: "Sample.tokens 中属于 response 后缀的 token 数量，不包含 prompt token 前缀。",
    aliases: ["generated length"],
    avoid: ["sequence length", "prompt length"],
    disambiguation: "len(tokens) 是 prompt+response；response_length 只计 response。",
    sourceRefIds: ["sample.append-response-tokens"],
    usedBy: ["act-3", "q4", "q5"],
  },
  {
    id: "loss-mask",
    zhLabel: "训练位置掩码",
    codeLabel: "loss_mask",
    definition: "在 response 空间标记哪些 token 位置可以对训练 loss 作贡献的掩码。",
    aliases: ["response loss mask", "action mask"],
    avoid: ["attention mask", "reward"],
    disambiguation: "它不是完整序列的 attention mask；在 Sample 中长度应与 response_length 相同。",
    sourceRefIds: ["sample.append-response-tokens", "rollout.convert-train-data"],
    usedBy: ["act-3", "act-4", "act-5", "act-6", "q5"],
  },
  {
    id: "rollout-log-prob",
    zhLabel: "rollout 动作对数概率",
    codeLabel: "rollout_log_probs",
    definition: "生成 policy 在 rollout 时对各 response 动作 token 记录的 log probability。",
    aliases: ["behavior log-prob"],
    avoid: ["current policy log-prob", "prompt log-prob"],
    disambiguation: "它记录生成当时的 policy；训练时重新计算的 current log-prob 属于另一阶段。",
    sourceRefIds: ["sample.append-response-tokens", "actor.train"],
    usedBy: ["act-3", "q4"],
  },
  {
    id: "raw-reward",
    zhLabel: "原始 reward",
    codeLabel: "Sample.reward / raw_reward",
    definition: "reward 函数对轨迹结果给出的未做组内后处理的评价值。",
    aliases: ["scalar reward"],
    avoid: ["advantage", "组内中心化 reward"],
    disambiguation: "Sample.reward 保存原始评价；converter 中的 rewards 可以是处理后的派生训练信号。",
    sourceRefIds: ["rollout.generate-and-rm", "rollout.convert-train-data"],
    usedBy: ["act-4", "act-5"],
  },
  {
    id: "centered-reward",
    zhLabel: "组内中心化 reward",
    codeLabel: "reward - group mean",
    definition: "每个同组候选的 raw reward 减去该组均值后得到的派生训练值。",
    aliases: ["group-centered reward"],
    avoid: ["标准化 reward", "normalized reward"],
    disambiguation: "math-2x2-v1 关闭 std normalization，所以只能称“中心化”，不能称“标准化”。它不写回 Sample.reward。",
    sourceRefIds: ["rollout.post-process-rewards", "rollout.convert-train-data"],
    usedBy: ["act-5", "q7"],
  },
  {
    id: "train-data",
    zhLabel: "派生训练数据",
    codeLabel: "train_data",
    definition: "converter 从 Sample 显式构造、再由 scheduler 分发给 trainer 的字段集合。",
    aliases: ["rollout train data", "derived train data"],
    avoid: ["raw Sample", "自动透传字段"],
    disambiguation: "新 Sample 字段不会自然进入 train_data；converter 和 per-rank packaging 必须显式传递。",
    sourceRefIds: ["rollout.convert-train-data", "rollout.split-train-data", "actor.consume-rollout-data"],
    usedBy: ["act-5", "act-6", "q7"],
  },
  {
    id: "terminal-status",
    zhLabel: "终止状态",
    codeLabel: "Sample.status",
    definition: "描述一次 generation 如何结束的状态，例如 COMPLETED、TRUNCATED 或 ABORTED。",
    aliases: ["sample status"],
    avoid: ["reward", "filter decision"],
    disambiguation: "status 描述终止方式；reward 评价结果；filter 决定 group 是否进入收集结果。",
    sourceRefIds: ["sample.apply-meta-info", "test.sample-status"],
    usedBy: ["act-1", "act-3", "act-4", "q6"],
  },
  {
    id: "dynamic-filter",
    zhLabel: "动态过滤",
    codeLabel: "dynamic filter",
    definition: "rollout 收集期间按完整 prompt group 判断 keep / drop 的可扩展选择步骤。",
    aliases: ["sample group filter"],
    avoid: ["逐 token mask", "reward 本身"],
    disambiguation: "filter 决定 group 是否被收集；loss_mask 决定已收集 response 的哪些位置可训练。",
    sourceRefIds: ["rollout.generate-async"],
    usedBy: ["act-4"],
  },
  {
    id: "weight-version",
    zhLabel: "生成权重版本",
    codeLabel: "weight_versions",
    definition: "记录 Sample 的 response 由哪个 rollout-engine policy 版本生成的历史信息。",
    aliases: ["policy version", "actor version"],
    avoid: ["当前 trainer 权重", "会被回写的全局版本"],
    disambiguation: "历史 Sample 保留生成当时版本；后续 optimizer step 与 weight sync 不会改写它。",
    sourceRefIds: ["sample.apply-meta-info", "test.sample-weight-version", "actor.update-weights"],
    usedBy: ["act-3", "act-6", "act-7", "q9"],
  },
  {
    id: "weight-sync",
    zhLabel: "权重发布 / 同步",
    codeLabel: "update_weights",
    definition: "把训练后的 actor 参数显式发布给 rollout engine，并等待发布边界完成的系统动作。",
    aliases: ["weight publication", "weight update"],
    avoid: ["optimizer step", "自动共享参数"],
    disambiguation: "optimizer step 更新训练侧 actor；weight sync 才让 SGLang 使用新版本。",
    sourceRefIds: ["loop.sync", "actor.update-weights"],
    usedBy: ["act-7", "q1", "q9"],
  },
  {
    id: "asynchronous-rollout",
    zhLabel: "异步 rollout",
    codeLabel: "async rollout",
    definition: "让下一轮 generation 与当前训练重叠，以改变时间调度但保留显式权重发布 barrier 的路径。",
    aliases: ["overlapped rollout"],
    avoid: ["无同步训练", "请求中途切权重"],
    disambiguation: "异步意味着阶段可以重叠，不意味着取消版本一致性；发布前仍需等待进行中的 generation。",
    sourceRefIds: ["loop.async", "actor.update-weights"],
    usedBy: ["act-7", "q9"],
  },
];
