import type { AssessmentQuestion, LessonAct, OverviewStep } from "../types";

export const sampleJourneyOverview = {
  title: "90 秒闭环速览",
  description: "先只回答“谁把数据交给谁”，暂不展开字段与算法公式。",
  totalSeconds: 90,
  steps: [
    {
      id: "overview-dataset",
      order: 1,
      actor: "Dataset",
      action: "把输入行构造成尚未完成的 Sample",
      passesTo: "DataSource",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-group",
      order: 2,
      actor: "DataSource",
      action: "复制 prompt，建立同组候选与独立身份",
      passesTo: "SGLang",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-generate",
      order: 3,
      actor: "SGLang",
      action: "生成 response，补齐 token、mask、log-prob 与状态",
      passesTo: "Reward / collect",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-reward",
      order: 4,
      actor: "Reward / collect",
      action: "评价结果，并收集满足协议的完整 group",
      passesTo: "RolloutManager",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-convert",
      order: 5,
      actor: "RolloutManager",
      action: "把 Sample 显式转换、排程为 trainer batch",
      passesTo: "Megatron actor",
      durationSeconds: 14,
      kind: "source-fact",
    },
    {
      id: "overview-train",
      order: 6,
      actor: "Megatron actor",
      action: "消费派生训练数据，执行 optimizer step",
      passesTo: "Weight sync",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-sync",
      order: 7,
      actor: "Weight sync",
      action: "把新 actor 权重发布给 rollout engine",
      passesTo: "下一轮 DataSource",
      durationSeconds: 13,
      kind: "source-fact",
    },
  ] satisfies OverviewStep[],
} as const;

export const sampleJourneyActs: LessonAct[] = [
  {
    id: "act-1",
    number: 1,
    slug: "birth",
    title: "第一幕：出生——数据行成为未完成的 Sample",
    shortTitle: "出生",
    durationMinutes: 2,
    drivingQuestion: "Dataset 读取数据时，是否已经 tokenization 并准备好了训练张量？",
    stage: {
      actor: "Dataset → Sample",
      visual: "两行 JSON 中的一行进入 Dataset，输出一张只点亮输入字段的 PENDING Sample 卡。",
    },
    fieldChanges: [
      "row.text → Sample.prompt",
      "row.label → Sample.label",
      "row.metadata → Sample.metadata",
      "tokens = []；response = \"\"；response_length = 0",
      "reward = None；loss_mask = None；status = PENDING",
    ],
    explanation: [
      {
        id: "act-1-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "Dataset 负责读取 JSONL / Parquet、选择 prompt / label / metadata，并构造 Sample。默认路径不会在这里把它变成 Megatron 可直接消费的 tensor batch。",
      },
      {
        id: "act-1-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "math-2x2-v1 使用两行算术 JSON 输入，并关闭 chat template，以便只观察 Sample 生命周期。输入、label 与 metadata 是稳定教学值。",
      },
      {
        id: "act-1-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "tools、多模态输入与 chat template 有各自的数据入口；它们会在后续内容中展开，不改变本幕要记住的初始边界。",
      },
    ],
    sourceRefIds: ["dataset.read-file", "dataset.construct-sample", "sample.dataclass"],
    glossaryTermIds: ["dataset-row", "sample-object", "terminal-status"],
    misconception: {
      belief: "Dataset row 一进入框架，就已经包含 prompt token 和 response 侧 mask。",
      correction: "默认路径在生成阶段才准备 prompt token，并在追加 response token 时维护 response 侧 mask 与 log-prob。",
    },
    microCheck: {
      prompt: "初始 Sample 的 tokens、reward 与 status 分别是什么？",
      answer: "tokens=[]、reward=None、status=PENDING。",
      feedback: "它已经是 Sample 对象，但还不是训练数据。",
    },
    transition: "一条 prompt 还不够做组内比较；下一步，它会先被复制成多个独立候选。",
  },
  {
    id: "act-2",
    number: 2,
    slug: "grouping",
    title: "第二幕：分组——一个 prompt 形成多个同组候选",
    shortTitle: "分组",
    durationMinutes: 2.5,
    drivingQuestion: "同一个 prompt 的两个候选，哪些身份应该相同，哪些必须不同？",
    stage: {
      actor: "DataSource",
      visual: "a0 与 a1 用同色 group 括号连接，却各自显示不同 index；第二行输入形成 b0 与 b1。",
    },
    fieldChanges: [
      "同组候选：group_index、prompt、label、metadata 内容相同",
      "物理实例：index 各不相同",
      "返回形状：list[group][sample]",
      "普通路径此时仍未产生 Sample.rollout_id",
    ],
    explanation: [
      {
        id: "act-2-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "RolloutDataSource.get_samples 使用 deepcopy 形成候选，为同一 prompt 分配相同 group_index，并给每条物理 Sample 分配独立 index。group_index 是分组身份，不是所有下游都会消费的训练主键。",
      },
      {
        id: "act-2-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "rollout_batch_size=2、n_samples_per_prompt=2，因此得到 2 组、4 条 Sample：a0/a1 与 b0/b1。固定 ID 只为可重复演示。",
      },
      {
        id: "act-2-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "partial rollout 可以让可恢复 group 优先于新数据重新入队；首课不把 buffer 描述成通用分布式消息队列。",
      },
    ],
    sourceRefIds: ["rollout.datasource-get-samples"],
    glossaryTermIds: ["prompt-group", "group-index", "sample-index"],
    misconception: {
      belief: "同一 prompt 的两个副本是重复数据，所以应该共享 index。",
      correction: "它们属于同一 prompt group，但每次 generation 是独立物理 Sample，必须拥有不同 index。",
    },
    microCheck: {
      prompt: "3 个 prompts、每个 prompt 生成 4 个候选，会得到多少 group 和 Sample？",
      answer: "3 个 group、12 条 Sample；组内 group_index 相同，所有 index 不同。",
      feedback: "prompt 数决定 group 数；每组候选数再决定物理 Sample 总数。",
    },
    transition: "身份已经建立，但这些同组候选仍是空白；现在 SGLang 要为它们各自生成 response。",
  },
  {
    id: "act-3",
    number: 3,
    slug: "generation",
    title: "第三幕：生成——token、mask、log-prob 与状态同时推进",
    shortTitle: "生成",
    durationMinutes: 4,
    drivingQuestion: "tokens 为什么比 response_length 长；工具 observation 为什么需要 mask 与占位 log-prob？",
    stage: {
      actor: "SGLang",
      visual: "prompt token 前缀先出现，response token 追加其后；每个 response 位置并排显示 log-prob、loss mask 与 weight version。",
    },
    fieldChanges: [
      "session_id: None → session-a0",
      "tokens: [] → prompt_ids → prompt_ids + response_ids",
      "response: \"\" → \"5\"；response_length: 0 → 1",
      "loss_mask: None → [1]；rollout_log_probs: None → [-0.08]",
      "weight_versions: [] → [actor@0]；status: PENDING → COMPLETED",
    ],
    explanation: [
      {
        id: "act-3-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "append_response_tokens 只在 response 空间维护 response_length、loss_mask 和 rollout_log_probs。模型动作位置可训练；工具或环境 token 可以 mask=0，并使用占位 log-prob。finish reason 再映射为 terminal status。",
      },
      {
        id: "act-3-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "a0 固定使用 5 个 prompt token、1 个 response token、log-prob -0.08 与 actor@0。token ID 和 session-a0 不是 tokenizer 或在线服务实测值。",
      },
      {
        id: "act-3-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "播放器逐 token 动画只是确定性教学回放；它不宣称默认生成接口必然以相同粒度 streaming。agent 工具调用会让 mask 对齐更丰富。",
      },
    ],
    sourceRefIds: [
      "rollout.generate",
      "sample.append-response-tokens",
      "sample.apply-meta-info",
      "test.sample-status",
      "test.sample-weight-version",
    ],
    glossaryTermIds: ["response-length", "loss-mask", "rollout-log-prob", "weight-version", "terminal-status"],
    misconception: {
      belief: "loss_mask 应与完整 tokens 等长，因此 prompt 位置也要在 Sample 中显式填 0。",
      correction: "Sample.loss_mask 位于 response 空间，长度等于 response_length；训练数据层随后把它对齐到完整序列。",
    },
    microCheck: {
      prompt: "5 个 prompt token，加上 2 个模型、2 个工具、1 个模型 token：三个长度是多少？",
      answer: "len(tokens)=10，response_length=5，len(loss_mask)=len(rollout_log_probs)=5；有效 response 长度为 3。",
      feedback: "prompt 前缀只计入 tokens；mask 与 rollout log-prob 在 response 空间对齐。",
    },
    transition: "现在知道模型做了什么、哪些位置是动作以及生成怎样结束，但还不知道结果值多少。",
  },
  {
    id: "act-4",
    number: 4,
    slug: "reward-and-collect",
    title: "第四幕：评价与收集——reward、status、filter 各司其职",
    shortTitle: "评价与收集",
    durationMinutes: 2.5,
    drivingQuestion: "reward 高，是否意味着全部 response token 都会产生更大的梯度？",
    stage: {
      actor: "Reward / collect",
      visual: "四条 Sample 获得 1/0/1/0 的 raw reward，再以完整 group 为单位进入 accepted 托盘。",
    },
    fieldChanges: ["Sample.reward: None → 1.0 或 0.0", "tokens、mask、status 等生成结果保持不变"],
    explanation: [
      {
        id: "act-4-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "默认顺序把 generation、sample hooks 与 reward evaluation 串起来。reward 评价轨迹结果，loss_mask 选择可训练 response token，status 描述生成怎样终止；三者职责不同。",
      },
      {
        id: "act-4-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "a0、b0 的 raw reward 为 1，a1、b1 为 0；四条均以 COMPLETED 结束。本例不通过网络调用 reward service。",
      },
      {
        id: "act-4-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "dynamic filter 可以按完整 group keep / drop；partial 模式还可能把 abort group 送回 buffer。首课只标出扩展点，不展开并发与恢复协议。",
      },
    ],
    sourceRefIds: ["rollout.generate-and-rm", "rollout.generate-async"],
    glossaryTermIds: ["raw-reward", "loss-mask", "terminal-status", "dynamic-filter"],
    misconception: {
      belief: "reward 为 1 时，mask 为 0 的 token 也会自动参与优化。",
      correction: "reward 仍会进入后续训练信号处理；mask 为 0 的位置不会因为高 reward 自动变成训练 action。",
    },
    microCheck: {
      prompt: "A、B 的 reward 都是 1，但 A 的 mask=[1]、B 的 mask=[0]。哪条有有效策略梯度位置？",
      answer: "A。B 没有有效训练 token。",
      feedback: "reward 评价结果；loss_mask 决定 response 中哪些位置可参与优化。",
    },
    transition: "accepted Sample 已满足 rollout 协议，但 Megatron 不直接消费这个 dataclass；中间还有显式转换边界。",
  },
  {
    id: "act-5",
    number: 5,
    slug: "conversion-and-schedule",
    title: "第五幕：交接与排程——从 Sample 到 train data",
    shortTitle: "交接与排程",
    durationMinutes: 4,
    drivingQuestion: "哪些值仍属于 raw Sample，哪些是转换、reward 处理和 batch 调度后才出现的派生数据？",
    stage: {
      actor: "RolloutManager",
      visual: "左栏锁定 raw Sample，右栏生成 train_data；Batch 计算器从 4 logical rollouts 推出 2 training steps。",
    },
    fieldChanges: [
      "reward → raw_reward 与 rewards（组内中心化 reward）",
      "index → sample_indices；缺失 rollout_id → 派生 rollout_ids",
      "loss_mask → loss_masks；同一 logical rollout → rollout_mask_sums",
      "4 logical rollouts ÷ global_batch_size 2 = 2 training steps",
    ],
    explanation: [
      {
        id: "act-5-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "RolloutManager 先验证并 flatten rollout 数据，再显式转换字段，最后按 logical rollout 构造 DP schedule。给 Sample 新增字段，不代表 trainer 会自动看到它。",
      },
      {
        id: "act-5-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "本例关闭 std normalization，所以 rewards 只展示 reward 减组均值后的组内中心化 reward：每组为 +0.5/-0.5。它是派生 train data，不写回 Sample.reward。",
      },
      {
        id: "act-5-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "一次逻辑 rollout fan-out 成多个物理训练片段时，同一逻辑 rollout 的派生片段共享 Sample.rollout_id，但每个物理 Sample 的 index 仍不同。默认 fixture 不启用 fan-out。",
      },
    ],
    sourceRefIds: [
      "rollout.manager-generate",
      "rollout.get-data",
      "rollout.post-process-rewards",
      "rollout.convert-train-data",
      "rollout.split-train-data",
      "schedule.build-dp-schedule",
      "test.dp-schedule-contract",
    ],
    glossaryTermIds: [
      "logical-rollout",
      "rollout-id",
      "centered-reward",
      "train-data",
      "rollout-batch",
      "training-step",
    ],
    misconception: {
      belief: "给 Sample 新增字段后，Megatron 会自然看到它。",
      correction: "训练侧需要的新字段必须被 converter 与 per-rank packaging 显式传递。",
    },
    microCheck: {
      prompt: "response_length=3 且 loss_mask=None；若 remove_sample=false/true，转换后的 mask 分别是什么？",
      answer: "false 时为 [1,1,1]；true 时为 [0,0,0]。",
      feedback: "缺失 mask 会按 response 长度补 1；移除训练贡献时再清零。",
    },
    transition: "旅程中的对象已经从 Sample 变成 trainer batch；下一幕用派生训练信号更新 actor。",
  },
  {
    id: "act-6",
    number: 6,
    slug: "training",
    title: "第六幕：训练——Sample 在边界处冻结，actor 参数开始变化",
    shortTitle: "训练",
    durationMinutes: 2.5,
    drivingQuestion: "Megatron 真正消费什么；mask 为 0 的 token 在这里发生什么？",
    stage: {
      actor: "Megatron actor",
      visual: "raw Sample 移入历史区；两个 training step 进入 actor，有效 mask 位置连向 loss 与 optimizer。",
    },
    fieldChanges: [
      "Sample 对象不再修改",
      "per-DP train data 被搬到设备并构造 microbatch schedule",
      "actor 参数从 actor@0 训练到 actor@1，但尚未发布到 SGLang",
    ],
    explanation: [
      {
        id: "act-6-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "actor 训练侧接收 per-DP train data，不接收 Sample dataclass。它基于配置准备 log-prob、advantage / returns 与 loss；有效 response-side mask 决定可贡献的位置。",
      },
      {
        id: "act-6-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "播放器用 actor@0 → actor@1 表示参数更新边界，不模拟真实张量、loss 数值、吞吐或 GPU 时长。",
      },
      {
        id: "act-6-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "PPO、GRPO、GSPO 与 CISPO 在训练信号和 loss 上有不同细节；首课只保留所有算法都必须面对的数据边界。",
      },
    ],
    sourceRefIds: ["actor.consume-rollout-data", "actor.train"],
    glossaryTermIds: ["train-data", "training-step", "loss-mask", "weight-version"],
    misconception: {
      belief: "trainer 会重新检查 prompt group，并根据 group_index 决定 loss。",
      correction: "trainer 看到的是 converter 与 scheduler 交付的字段；分组处理与 logical rollout 归一化信息必须在边界前正确准备。",
    },
    microCheck: {
      prompt: "把 status、rollout_mask_sums、optimizer step 分到 raw Sample、derived train data、actor state 三栏。",
      answer: "status 属于 raw Sample；rollout_mask_sums 属于 derived train data；optimizer step 属于 actor state。",
      feedback: "同一页面可以并排展示三层状态，但不能把它们混成同一个对象。",
    },
    transition: "actor 已更新，rollout engine 却仍可能持有旧权重；下一幕完成显式发布边界。",
  },
  {
    id: "act-7",
    number: 7,
    slug: "weight-return",
    title: "第七幕：权重回流——闭环真正闭合",
    shortTitle: "权重回流",
    durationMinutes: 2.5,
    drivingQuestion: "optimizer step 完成后，为什么不能假设下一次 SGLang generation 已经使用新 actor？",
    stage: {
      actor: "Weight sync",
      visual: "Actor 显示 actor@1/unpublished；同步完成后 SGLang 才从 actor@0 切到 actor@1，历史卡片保持不变。",
    },
    fieldChanges: [
      "Megatron actor: actor@0 → actor@1",
      "SGLang engine: actor@0 → actor@1（显式同步完成后）",
      "历史 Sample.weight_versions 保持 actor@0",
      "下一轮 Sample 才记录 actor@1",
    ],
    explanation: [
      {
        id: "act-7-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "默认同步循环在当前训练后显式调用 actor_model.update_weights，再进入下一次 generation。同步改变 rollout engine 的系统状态，不回写历史 Sample。",
      },
      {
        id: "act-7-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "actor@0/actor@1 和时间块宽度用于表达版本与相对顺序，不是实际 checkpoint 名、transport trace 或性能 benchmark。",
      },
      {
        id: "act-7-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "async 可以让 rollout(i+1) 与 train(i) 重叠，因此它可能仍由 actor@i 生成；发布前会等待进行中的 generation，避免请求中途切换权重。",
      },
    ],
    sourceRefIds: ["loop.sync", "loop.async", "actor.update-weights"],
    glossaryTermIds: ["weight-version", "weight-sync", "asynchronous-rollout"],
    misconception: {
      belief: "optimizer step 一结束，正在生成的所有请求会自然切到新权重。",
      correction: "权重发布是显式系统边界；异步路径还会先让重叠中的 generation 完成，再发布新版本。",
    },
    microCheck: {
      prompt: "异步时间线中的 rollout(i+1) 为什么可能仍记录 actor@i？",
      answer: "它与 train(i) 重叠，在新权重发布前已经开始；发布边界会先等待进行中的 generation。",
      feedback: "异步改变重叠关系，不取消一致的权重发布边界。",
    },
    transition: "闭环完成：下一条 Sample 会记录新 policy 做了什么，而历史 Sample 继续保留生成当时的版本。",
  },
];

export const sampleJourneyAssessment = {
  id: "core.sample-journey.check",
  version: 1,
  title: "章末知识检查",
  description: "可无限重试。至少答对 7 题，并且 q4、q5、q8 必须正确。",
  questions: [
    {
      id: "q1",
      type: "ordering",
      prompt: "把一条 Sample 的七段闭环按发生顺序排列。",
      options: [
        { id: "dataset", label: "Dataset 构造初始 Sample" },
        { id: "group", label: "DataSource 建立同组候选" },
        { id: "generate", label: "SGLang 生成 response" },
        { id: "reward", label: "reward / collect 评价并收集" },
        { id: "convert", label: "RolloutManager 转换与排程" },
        { id: "train", label: "Megatron actor 训练" },
        { id: "sync", label: "weight sync 发布新权重" },
      ],
      correctOrder: ["dataset", "group", "generate", "reward", "convert", "train", "sync"],
      required: false,
      answerSummary: "Dataset → 分组 → 生成 → reward/collect → 转换/排程 → train → weight sync。",
      feedback: {
        correct: "顺序正确。你已经能复原闭环骨架。",
        incorrect: "先只追踪交接关系，不要把字段细节混进顺序。回看 90 秒闭环。",
      },
      returnTo: { label: "回看 90 秒闭环", href: "/learn/sample-journey#overview" },
    },
    {
      id: "q2",
      type: "multiple",
      prompt: "关于刚由 Dataset 构造出的初始 Sample，哪些说法正确？",
      options: [
        { id: "semantic", label: "已经有 prompt、label 与 metadata" },
        { id: "pending", label: "status 为 PENDING" },
        { id: "empty", label: "tokens 与 response 仍为空" },
        { id: "rewarded", label: "已经有组内中心化 reward" },
        { id: "tensor", label: "已经是 Megatron tensor batch" },
      ],
      correctOptionIds: ["semantic", "pending", "empty"],
      required: false,
      answerSummary: "初始 Sample 保存语义输入，生成与训练侧字段仍未准备。",
      feedback: {
        correct: "正确。Sample 已出生，但还没有经过生成、评价与转换。",
        incorrect: "注意时间点：Dataset 只完成了 Sample 的初始语义字段。",
      },
      returnTo: { label: "回到第一幕", href: "/learn/sample-journey#act-1", actId: "act-1" },
    },
    {
      id: "q3",
      type: "single",
      prompt: "3 个 prompts、每个 prompt 生成 N=4 个同组候选，会得到多少 group 与物理 Sample？",
      options: [
        { id: "3-12", label: "3 个 group，12 条 Sample" },
        { id: "12-12", label: "12 个 group，12 条 Sample" },
        { id: "3-4", label: "3 个 group，4 条 Sample" },
        { id: "4-12", label: "4 个 group，12 条 Sample" },
      ],
      correctOptionIds: ["3-12"],
      required: false,
      answerSummary: "prompt 数决定 group 数；每组 N 个候选，所以 3×4=12 条 Sample。",
      feedback: {
        correct: "正确。同组 group_index 相同，但物理 index 各不相同。",
        incorrect: "不要把候选数当成 group 数：一个 prompt 对应一个 group。",
      },
      returnTo: { label: "回到第二幕", href: "/learn/sample-journey#act-2", actId: "act-2" },
    },
    {
      id: "q4",
      type: "single",
      prompt: "prompt 有 6 个 token、response 有 4 个 token。哪组长度关系正确？",
      options: [
        { id: "10-4-4", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=4" },
        { id: "10-10-4", label: "len(tokens)=10，response_length=10，len(rollout_log_probs)=4" },
        { id: "6-4-10", label: "len(tokens)=6，response_length=4，len(rollout_log_probs)=10" },
        { id: "10-4-10", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=10" },
      ],
      correctOptionIds: ["10-4-4"],
      required: true,
      answerSummary: "tokens 包含 prompt 前缀和 response 后缀；response 元数据只在 response 空间对齐。",
      feedback: {
        correct: "关键不变量正确。",
        incorrect: "这是一道必对题：把完整 tokens 与 response-side 元数据分开计算。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q5",
      type: "single",
      prompt: "response 依次包含 2 个模型 token、2 个工具 token、3 个模型 token。正确 mask 与有效长度是什么？",
      options: [
        { id: "mask-correct", label: "[1,1,0,0,1,1,1]，有效长度 5" },
        { id: "mask-all", label: "[1,1,1,1,1,1,1]，有效长度 7" },
        { id: "mask-tool", label: "[0,0,1,1,0,0,0]，有效长度 2" },
        { id: "mask-short", label: "[1,1,1,1,1]，有效长度 5" },
      ],
      correctOptionIds: ["mask-correct"],
      required: true,
      answerSummary: "模型动作位置为 1，工具 observation 位置为 0；mask 仍与全部 response 位置等长。",
      feedback: {
        correct: "关键 mask 对齐正确。",
        incorrect: "这是一道必对题：工具 token 仍占 response 位置，但不贡献训练 mask。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q6",
      type: "single",
      prompt: "finish reason 与 terminal status 的正确映射是哪一项？",
      options: [
        { id: "correct", label: "stop→COMPLETED，length→TRUNCATED，abort→ABORTED" },
        { id: "swap", label: "stop→TRUNCATED，length→COMPLETED，abort→ABORTED" },
        { id: "all", label: "三者都映射为 COMPLETED" },
        { id: "pending", label: "三者都保持 PENDING" },
      ],
      correctOptionIds: ["correct"],
      required: false,
      answerSummary: "stop、length、abort 分别映射为 COMPLETED、TRUNCATED、ABORTED。",
      feedback: {
        correct: "正确。status 描述生成如何结束。",
        incorrect: "回看生成终止阶段，不要把 reward 与 terminal status 混淆。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q7",
      type: "multiple",
      prompt: "下面哪些值不是 raw Sample 字段，而是在转换后才出现的 derived train data？",
      options: [
        { id: "centered", label: "组内中心化 reward" },
        { id: "mask-sum", label: "rollout_mask_sums" },
        { id: "status", label: "terminal status" },
        { id: "prompt", label: "prompt" },
      ],
      correctOptionIds: ["centered", "mask-sum"],
      required: false,
      answerSummary: "组内中心化 reward 与 rollout_mask_sums 都在 Sample→train data 边界派生。",
      feedback: {
        correct: "正确。你没有把派生训练数据伪装成 Sample 字段。",
        incorrect: "锁定 raw Sample 与 derived train data 两栏，再看字段从哪里出现。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q8",
      type: "single",
      prompt: "一次逻辑 rollout fan-out 成多个训练片段时，为什么它们共享 rollout_id、却拥有不同 index？",
      options: [
        {
          id: "identity-correct",
          label: "rollout_id 标记同一逻辑执行，index 标记各物理 Sample，避免重复计数又保留独立身份",
        },
        { id: "duplicate", label: "它们其实是完全相同的重复对象，所以两个 ID 都应该相同" },
        { id: "group", label: "rollout_id 等同于 prompt group 的 group_index" },
        { id: "random", label: "两种 ID 都只是随机展示值，下游不使用" },
      ],
      correctOptionIds: ["identity-correct"],
      required: true,
      answerSummary: "rollout_id 聚合逻辑执行；index 保持每个物理训练片段的唯一身份。",
      feedback: {
        correct: "关键身份边界正确。",
        incorrect: "这是一道必对题：不要把 prompt group、逻辑 rollout 与物理 Sample 合并。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q9",
      type: "single",
      prompt: "异步路径中的 rollout(i+1) 为什么可能仍使用 actor@i？",
      options: [
        { id: "overlap", label: "它与 train(i) 重叠并在新权重发布前开始；发布前会等待进行中的 generation" },
        { id: "rewrite", label: "新权重会在完成后回写历史 Sample，所以版本无所谓" },
        { id: "no-sync", label: "异步路径永远不做 weight sync" },
        { id: "mid-request", label: "请求进行到一半时会无条件切到 actor@i+1" },
      ],
      correctOptionIds: ["overlap"],
      required: false,
      answerSummary: "生成与训练可以重叠，但显式发布边界仍要等待进行中的 generation，避免请求中途混用版本。",
      feedback: {
        correct: "正确。异步改变时间重叠，不取消版本边界。",
        incorrect: "对照 sync/async 时间线，找到 generation、train 与 weight barrier 的相对位置。",
      },
      returnTo: { label: "回到第七幕", href: "/learn/sample-journey#act-7", actId: "act-7" },
    },
  ] satisfies AssessmentQuestion[],
  completion: {
    minCorrect: 7,
    requiredQuestionIds: ["q4", "q5", "q8"],
    requiredActIds: ["act-1", "act-2", "act-3", "act-4", "act-5", "act-6", "act-7"],
    unlimitedRetries: true,
    progressScope: "device-local",
  },
} as const;

export const sampleJourneyLesson = {
  metadata: {
    schemaVersion: 1,
    id: "core.sample-journey",
    kind: "lesson",
    locale: "zh-CN",
    route: "/learn/sample-journey",
    title: "一条 Sample 的旅程",
    summary: "跟踪一行数据如何成为可信的训练更新，以及新权重怎样影响下一条 Sample。",
    audiences: ["researcher", "engineer"],
    level: "slime-intro",
    duration: { minMinutes: 25, maxMinutes: 30, includesAssessment: true },
    workflowStatus: "ready",
    freshnessStatus: "current",
    visibility: "public",
    lessonRevision: 1,
    prerequisites: ["concept.rl-loop-basics"],
    learningObjectives: [
      "按顺序复述 Dataset → DataSource → SGLang → reward/collect → train data → Megatron → weight sync 闭环。",
      "区分 dataset row、prompt group、物理 Sample、逻辑 rollout、rollout batch 与 training step。",
      "解释 tokens、response_length、loss_mask、rollout_log_probs、reward 与 status 的边界。",
      "检查 response 侧长度、逻辑身份与 batch 守恒三个关键不变量。",
      "指出 optimizer step 与权重发布的边界，并对比同步与异步的最小差异。",
    ],
    learningObjectiveIds: [
      "sample-lifecycle",
      "token-alignment",
      "identity-boundaries",
      "batch-conservation",
      "weight-publication-boundary",
    ],
    completion: {
      assessmentId: "core.sample-journey.check",
      assessmentVersion: 1,
      minCorrect: 7,
      requiredQuestionIds: ["q4", "q5", "q8"],
      requiredActs: [1, 2, 3, 4, 5, 6, 7],
    },
    baseline: {
      repository: "THUDM/slime",
      nearestTag: "v0.3.1",
      describe: "v0.3.1-1-g06ffdbe2",
      commit: "06ffdbe22be068b52f9ed0fc318c473f7030197e",
    },
    fixtureIds: ["math-2x2-v1"],
    glossaryTermIds: [
      "dataset-row",
      "sample-object",
      "prompt-group",
      "group-index",
      "sample-index",
      "logical-rollout",
      "rollout-id",
      "rollout-batch",
      "training-step",
      "response-length",
      "loss-mask",
      "rollout-log-prob",
      "raw-reward",
      "dynamic-filter",
      "centered-reward",
      "train-data",
      "terminal-status",
      "weight-version",
      "weight-sync",
      "asynchronous-rollout",
    ],
    sourceRefIds: [
      "sample.dataclass",
      "dataset.construct-sample",
      "rollout.datasource-get-samples",
      "sample.append-response-tokens",
      "rollout.convert-train-data",
      "schedule.build-dp-schedule",
      "actor.train",
      "actor.update-weights",
    ],
    testRefIds: ["test.sample-contract", "test.dp-schedule-contract"],
    owners: {
      content: "project-initiator",
      technicalReview: "project-initiator-or-designated-slime-reviewer",
    },
  },
  hook: {
    question: "同样答对，为什么一个 Sample 完全不学习？",
    sampleA: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[1])',
    sampleB: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[0])',
    resolution:
      "reward 评价结果；loss_mask 决定 response 中哪些 token 能参与优化。B 没有有效训练 token。",
    revealAfterActId: "act-5",
  },
  invariants: [
    "tokens = prompt token 前缀 + response token 后缀",
    "loss_mask 存在时：len(loss_mask) == response_length",
    "rollout_log_probs 存在时：len(rollout_log_probs) == response_length",
    "一次逻辑 rollout 的派生片段共享 Sample.rollout_id；每个物理 Sample 的 index 仍不同",
  ],
  overview90s: sampleJourneyOverview,
  acts: sampleJourneyActs,
  assessment: sampleJourneyAssessment,
  closingMemory:
    "Sample 记录模型在某个 policy 版本下做了什么；train data 规定 trainer 怎样聚合它；weight sync 决定下一条 Sample 由哪个 policy 产生。",
  scopeNotice: {
    sourceFact: "带“源码事实”的结论已对照固定 commit 06ffdbe2。",
    teachingFixture: "带“教学 fixture”的数值只用于稳定讲解，不是实测 trace 或性能 benchmark。",
    advancedPreview: "带“进阶预告”的内容只标出下一步，不作为本课完成要求。",
  },
} as const;
