import type { AssessmentQuestion, LessonAct, OverviewStep } from "../types";

export const sampleJourneyOverview = {
  title: "先听一遍它的旅程",
  description: "这是七个角色的技术速览：先只看谁把记录交给谁。字段、公式与源码，会在每一幕慢慢展开。",
  totalSeconds: 90,
  steps: [
    {
      id: "overview-dataset",
      order: 1,
      actor: "Dataset",
      action: "把输入行构造成尚未完成的 Sample",
      passesTo: "DataSource",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-group",
      order: 2,
      actor: "DataSource",
      action: "复制 prompt，建立同组候选与独立身份",
      passesTo: "SGLang",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-generate",
      order: 3,
      actor: "SGLang",
      action: "生成 response，补齐 token、mask、log-prob 与状态",
      passesTo: "Reward → collect",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-reward",
      order: 4,
      actor: "Reward → collect",
      action: "逐条评价结果，再按完整 group 收回",
      passesTo: "RolloutManager",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-convert",
      order: 5,
      actor: "RolloutManager",
      action: "把 Sample 显式转换、排程为 trainer batch",
      passesTo: "Megatron actor",
      durationSeconds: 14,
      kind: "source-fact",
    },
    {
      id: "overview-train",
      order: 6,
      actor: "Megatron actor",
      action: "消费派生训练数据，执行 optimizer step",
      passesTo: "Weight sync",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-sync",
      order: 7,
      actor: "Weight sync",
      action: "把新 actor 权重发布给 rollout engine",
      passesTo: "下一轮 DataSource",
      durationSeconds: 13,
      kind: "source-fact",
    },
  ] satisfies OverviewStep[],
} as const;

export const sampleJourneyActs: LessonAct[] = [
  {
    id: "act-1",
    number: 1,
    slug: "birth",
    title: "第一幕：出生——一行数据有了 Sample 的形状",
    shortTitle: "出生",
    durationMinutes: 2,
    drivingQuestion: "这行数据刚进入 slime，就已经变成模型能训练的张量了吗？",
    stage: {
      actor: "Dataset → Sample",
      visual: "先把时间停在模型回答之前。我们只看一条记录：哪些信息已经写进 Sample，哪些位置仍然空着。",
    },
    narrative: {
      kicker: "先把时间停在模型开口之前",
      title: "一行 JSON，刚刚走进 slime。",
      paragraphs: [
        "它带着一道题、参考答案和来源说明。除此之外，几乎还是一张白纸：模型没有回答，评价没有发生，训练更没有开始。",
        "Dataset 做的第一件事很克制。它把外部记录整理成框架内部统一的 Sample，让这条记录获得继续穿过系统的形状；后面的生成、评分与训练痕迹，要等旅程真正发生后才会写进来。",
      ],
      directAnswer:
        "没有。默认教学路径此时只把 `text`、`label` 和 `metadata` 放进 `Sample`；`tokens` 仍是空列表，`reward` 与 `loss_mask` 仍是 `None`，更没有 trainer 能直接使用的 tensor batch。",
      evidenceLead: "直觉已经有了。现在用字段和源码，把这条边界钉牢。",
      takeaway: "`PENDING` 不是失败。它只是说明：这条记录已经出生，故事还没有发生。",
    },
    fieldChanges: [
      "题目进入档案：`row.text → Sample.prompt`",
      "参考答案与来源被保留：`row.label / metadata → Sample.label / metadata`",
      "模型尚未回答：`tokens=[]`、`response=\"\"`、`response_length=0`",
      "评价尚未发生：`reward=None`、`loss_mask=None`",
      "生命周期刚刚开始：`status=PENDING`",
    ],
    explanation: [
      {
        id: "act-1-fact",
        kind: "source-fact",
        title: "Dataset 只完成第一道翻译",
        body: "源码先从 JSONL 或 Parquet 读出一行，再取出 prompt、label 与 metadata，调用 `Sample(...)` 构造框架内对象。这一步保存的是语义输入，不是 Megatron 可直接消费的训练张量。",
      },
      {
        id: "act-1-fixture",
        kind: "teaching-fixture",
        title: "我们先把岔路关掉",
        body: "教学 fixture 只放入两道算术题，并关闭 chat template。这样不是说 slime 只能处理简单文本，而是为了让你先看清 `Sample` 怎样出生，不被模板、工具和多模态输入分散注意力。",
      },
      {
        id: "act-1-preview",
        kind: "advanced-preview",
        title: "以后，它还会带上更多行李",
        body: "真实任务可以把 tools 放进 metadata，也可以带入多模态字段或应用 chat template。入口会更丰富，但本幕的边界不变：Dataset 构造的是初始 `Sample`，不是最终训练 batch。",
      },
    ],
    sourceRefIds: ["dataset.read-file", "dataset.construct-sample", "sample.dataclass"],
    glossaryTermIds: ["dataset-row", "sample-object", "terminal-status"],
    misconception: {
      belief: "只要数据行进入框架，token、mask 和训练张量就都准备好了。",
      correction:
        "没有。默认路径在这一幕不会把 token ID 写入 `Sample.tokens`，`loss_mask` 也尚未产生；即使启用长度过滤时会借助 tokenizer 检查长度，这仍不等于构造训练张量。",
    },
    microCheck: {
      prompt: "此刻的 Sample 已经拥有什么，又还缺什么？",
      answer:
        "已有 `prompt`、`label` 与 `metadata`；`tokens=[]`、`reward=None`、`loss_mask=None`，`status=PENDING`。",
      feedback: "它已经是框架内的 `Sample`，却还不是 trainer 能消费的训练数据。",
    },
    transition: "它有了身体，却还是孤身一条记录。要比较回答的好坏，下一幕先让同一道题长出多个候选。",
  },
  {
    id: "act-2",
    number: 2,
    slug: "grouping",
    title: "第二幕：分组——同一道题，先摆出两个回答席位",
    shortTitle: "分组",
    durationMinutes: 2.5,
    drivingQuestion: "为什么同一道题要复制两份？复制后，哪些相同，哪些必须不同？",
    stage: {
      actor: "DataSource",
      visual: "先跟着算术题 `3 + 2 = ?` 走一遍：它会变成同组的 a0 与 a1，随后各自去经历一次生成。",
    },
    narrative: {
      kicker: "同一道题，为什么要走两遍？",
      title: "DataSource 没有改题，只是替它摆出两把椅子。",
      paragraphs: [
        "上一幕只有一道题：`3 + 2 = ?`。如果模型只回答一次，我们只能知道这一次答得怎样，却无法把同一道题的多次尝试放在一起比较。于是 DataSource 先不催模型开口，而是从同一条 prompt 深拷贝出两个候选：a0 和 a1。",
        "它们像拿着同一张试卷走进两个考场：`prompt`、`label` 与 `metadata` 的内容相同，`group_index` 也同为 0；但它们的 `index` 分别是 0 和 1。共享 `group_index` 是在说“以后把我们放在一起比较”，不同 `index` 则是在说“我们是两次彼此独立的生成记录”。",
      ],
      directAnswer:
        "同组候选拥有相同的 `prompt`、`label`、`metadata` 内容与 `group_index`；每条候选必须拥有不同的 `index`。一句话：`group_index` 回答“谁该一起比较”，`index` 回答“眼前究竟是哪一条记录”。",
      evidenceLead: "先认清这两张身份证，再看 DataSource 在源码里怎样发放它们。",
      takeaway: "相同的题目，不等于相同的尝试。同组让比较有意义，独立身份让每次生成都能被追踪。",
    },
    walkthrough: {
      kicker: "本课实例 · 先只看 group 0",
      title: "一道题，怎样变成两次独立尝试",
      introduction: "沿着箭头只看三件事：题目从哪里来、DataSource 做了什么、两条候选怎样认出彼此。",
      steps: [
        {
          label: "01 · 进入 DataSource",
          title: "此刻还只有一道题",
          body: "Sample 已经保存题目，却还没有被分组，也没有任何模型回答。",
          facts: [
            "prompt = \"3 + 2 = ?\"",
            "group_index = None",
            "index = None",
          ],
        },
        {
          label: "02 · 复制并编号",
          title: "为它安排两个回答席位",
          body: "DataSource 用 deepcopy 造出两个彼此独立的候选，再给它们写入组号与记录号。",
          facts: [
            "n_samples_per_prompt = 2",
            "deepcopy(prompt_sample)",
            "返回形状 = list[group][sample]",
          ],
        },
        {
          label: "03 · 离开 DataSource",
          title: "同组，但不是同一条记录",
          body: "a0 与 a1 会回答同一道题；下一幕里，它们可以生成完全不同的答案。",
          facts: [
            "a0 → group_index 0 · index 0",
            "a1 → group_index 0 · index 1",
            "response 仍为空",
          ],
        },
      ],
      caption: "第二道题 `4 + 3 = ?` 同理形成 group 1：b0 的 index 为 2，b1 的 index 为 3。本 fixture 因而得到 2 组、4 条 Sample。",
    },
    fieldChanges: [
      "一条 prompt 变成两个候选：`n_samples_per_prompt=2`",
      "同组标记被写入：a0 与 a1 的 `group_index=0`",
      "独立身份被写入：a0 的 `index=0`，a1 的 `index=1`",
      "题目内容不变，生成仍未开始：两条 `response` 都是空字符串",
      "普通路径此时仍未产生 `Sample.rollout_id`",
    ],
    explanation: [
      {
        id: "act-2-fact",
        kind: "source-fact",
        title: "源码真的做了这三步",
        body: "`RolloutDataSource.get_samples` 逐条取出 `prompt_sample`，在循环中调用 `deepcopy`，给副本写入 `group_index` 与递增的 `index`，再把同组副本装进一个列表。外层列表装 group，内层列表装该 prompt 的候选。",
      },
      {
        id: "act-2-fixture",
        kind: "teaching-fixture",
        title: "为什么本页恰好是四张卡",
        body: "教学 fixture 设置 `rollout_batch_size=2`，所以一次取两道 prompt；又设置 `n_samples_per_prompt=2`，所以每道题各有两个候选。结果是 2 个 group、4 条 Sample：a0/a1 与 b0/b1。a0 这类 ID 只为稳定演示，生产源码真正分配的是数值 `group_index` 与 `index`。",
      },
      {
        id: "act-2-preview",
        kind: "advanced-preview",
        title: "deepcopy 解决的不是“多一张卡”这么简单",
        body: "深拷贝让候选拥有内容相同、对象彼此独立的可变字段；以后修改 a0 的 metadata，不会顺手改掉 a1。partial rollout 还可以让可恢复 group 重新入队，但那是后续课程，本幕先守住“同组不等于同一实例”。",
      },
    ],
    sourceRefIds: ["rollout.datasource-get-samples"],
    glossaryTermIds: ["prompt-group", "group-index", "sample-index"],
    misconception: {
      belief: "a0 和 a1 的题目完全一样，所以它们就是两份无意义的重复数据。",
      correction: "题目相同正是为了形成可比较的候选；两条记录会分别生成、分别记录 log-prob、分别得到 reward，因此必须有不同 `index`。",
    },
    microCheck: {
      prompt: "3 个 prompts、每个 prompt 生成 4 个候选，会得到多少 group 和 Sample？",
      answer: "3 个 group、12 条 Sample；组内 group_index 相同，所有 index 不同。",
      feedback: "prompt 数决定 group 数；每组候选数再决定物理 Sample 总数。",
    },
    transition: "身份已经建立，但这些同组候选仍是空白；现在 SGLang 要为它们各自生成 response。",
  },
  {
    id: "act-3",
    number: 3,
    slug: "generation",
    title: "第三幕：生成——a0 终于得到一个回答",
    shortTitle: "生成",
    durationMinutes: 4,
    drivingQuestion: "SGLang 只回答了一个“5”，为什么 Sample 里却同时多出这么多字段？",
    stage: {
      actor: "SGLang",
      visual: "只跟随 a0：先准备请求，再把回答 token 接到 prompt 后面，最后记录这次生成怎样结束。",
    },
    narrative: {
      kicker: "两把椅子已经摆好，模型现在才开口",
      title: "a0 带着一道题进入 SGLang，回来时多了一段可训练的经历。",
      paragraphs: [
        "出发前，a0 只知道自己的题目。生成路径先把 prompt 准备成 token ID，并为这次请求留下 `session_id`；在本课的固定示例里，`3 + 2 = ?` 对应 5 个 prompt token。它们只是输入前缀，还不是模型的回答。",
        "随后 SGLang 使用 `actor@0` 生成了一个 token：ID 25，解码后是“5”。这个 token 被接到 prompt token 后面，于是 `tokens` 从 5 项变成 6 项；而 `response_length` 只数回答部分，所以它是 1。",
        "回答文本是给人读的，`loss_mask` 与 `rollout_log_probs` 则是留给训练的账本：前者说明这个回答位置是否算作模型动作，后者记录生成它时旧 policy 给出的 log probability。finish reason 最后把状态写成 `COMPLETED`，`weight_versions` 则留下“这段回答由 actor@0 生成”的历史。",
      ],
      directAnswer:
        "因为训练需要的不只是“模型说了什么”，还要知道“它生成了哪些 token、当时给这些动作多大概率、哪些位置可以训练、生成怎样结束、使用的是哪一版权重”。`response` 保存可读答案，其余字段保存可对齐、可追溯的生成证据。",
      evidenceLead: "先把 a0 的三个时刻并排看清，再讨论每个数组为什么必须对齐。",
      takeaway: "`response` 讲述答案；token、mask、log-prob、status 与权重版本，保存答案诞生的过程。",
    },
    walkthrough: {
      kicker: "本课实例 · 只跟随 a0",
      title: "一个“5”写回 Sample 时，究竟发生了什么",
      introduction: "不要一次记住所有字段。先按时间读：请求前、请求准备好、生成完成。",
      steps: [
        {
          label: "01 · 请求前",
          title: "题目在，回答还不在",
          body: "a0 已经拥有组号和身份，但它仍处于等待生成的 PENDING 状态。",
          facts: [
            "prompt = \"3 + 2 = ?\"",
            "tokens = []",
            "response = \"\"",
          ],
        },
        {
          label: "02 · 准备 SGLang 请求",
          title: "先放入 prompt 前缀",
          body: "生成路径准备输入 token；session 用来标识或路由这次请求，本课值是固定的教学数据。",
          facts: [
            "session_id = session-a0",
            "tokens = [11, 12, 13, 14, 15]",
            "response_length = 0",
          ],
        },
        {
          label: "03 · 回答并结束",
          title: "response token 接在 prompt 后面",
          body: "SGLang 返回 token 25，也就是“5”；Sample 同步保存动作概率、训练掩码和终止信息。",
          facts: [
            "tokens = [11, 12, 13, 14, 15, 25]",
            "response = \"5\" · response_length = 1",
            "loss_mask = [1] · log_probs = [-0.08]",
            "status = COMPLETED · actor@0",
          ],
        },
      ],
      caption: "最容易混淆的一点：`tokens` 保存 prompt + response，所以长度是 6；`response_length`、`loss_mask` 与 `rollout_log_probs` 只站在 response 一侧，所以长度都是 1。",
    },
    fieldChanges: [
      "请求获得身份：`session_id: None → session-a0`",
      "输入先成为 token 前缀：`tokens: [] → [11, 12, 13, 14, 15]`",
      "回答 token 接在末尾：`tokens → [11, 12, 13, 14, 15, 25]`",
      "可读答案被写回：`response: \"\" → \"5\"`，`response_length: 0 → 1`",
      "回答位置获得训练账本：`loss_mask=[1]`，`rollout_log_probs=[-0.08]`",
      "这次生成封存为历史：`status=COMPLETED`，`weight_versions=[actor@0]`",
    ],
    explanation: [
      {
        id: "act-3-fact",
        kind: "source-fact",
        title: "源码把一次生成分成准备、调用、写回",
        body: "`generate` 先准备 prompt IDs，再把请求发给 SGLang；响应回来后，`append_response_tokens` 把新 token 接到 `Sample.tokens`，同时更新 `response`、`response_length`、`loss_mask` 与 `rollout_log_probs`。最后，meta info 中的 finish reason 被映射为 terminal status。",
      },
      {
        id: "act-3-fixture",
        kind: "teaching-fixture",
        title: "为什么这里的数字可以逐项对上",
        body: "a0 在 fixture 中固定使用 5 个 prompt token 和 1 个 response token；回答 token 25 解码为“5”，对应 rollout log-prob 为 -0.08，生成权重版本为 actor@0。token ID 与 `session-a0` 是为了稳定回放而固定的值，不是线上 tokenizer 或 SGLang 服务的实测输出。",
      },
      {
        id: "act-3-preview",
        kind: "advanced-preview",
        title: "等单轮生成清楚后，再加入工具 observation",
        body: "本例只有一个模型动作，因此 `loss_mask=[1]` 很直观。agent 场景还会把工具或环境 observation token 接进 response 空间；这些位置可以用 mask 0 与占位 log-prob 表示。播放器只是确定性教学回放，不承诺生产请求一定按相同粒度 streaming。",
      },
    ],
    sourceRefIds: [
      "rollout.generate",
      "sample.append-response-tokens",
      "sample.apply-meta-info",
      "test.sample-status",
      "test.sample-weight-version",
    ],
    glossaryTermIds: ["response-length", "loss-mask", "rollout-log-prob", "weight-version", "terminal-status"],
    misconception: {
      belief: "`tokens` 有 6 项，所以 `loss_mask` 和 `rollout_log_probs` 也应该有 6 项。",
      correction: "`tokens` 包含 5 个 prompt token 与 1 个 response token；Sample 中的 `loss_mask` 和 `rollout_log_probs` 只描述 response 空间，所以各有 1 项。训练数据层随后才把 mask 对齐到完整序列。",
    },
    microCheck: {
      prompt: "5 个 prompt token，加上 2 个模型、2 个工具、1 个模型 token：三个长度是多少？",
      answer: "len(tokens)=10，response_length=5，len(loss_mask)=len(rollout_log_probs)=5；有效 response 长度为 3。",
      feedback: "prompt 前缀只计入 tokens；mask 与 rollout log-prob 在 response 空间对齐。",
    },
    transition: "现在知道模型做了什么、哪些位置是动作以及生成怎样结束，但还不知道结果值多少。",
  },
  {
    id: "act-4",
    number: 4,
    slug: "reward-and-collect",
    title: "第四幕：评价与收集——给答案打分，但不把队伍拆散",
    shortTitle: "评价与收集",
    durationMinutes: 2.5,
    drivingQuestion: "a1 的 reward 是 0，为什么 collect 没有把它丢掉？",
    stage: {
      actor: "Reward → collect",
      visual: "先判四条回答，再按原来的两组收回：group 0 带着 1/0，group 1 也带着 1/0，一条都不偷偷消失。",
    },
    narrative: {
      kicker: "模型停笔了，判卷才刚开始",
      title: "终点线与判卷桌，是两个不同的地方。",
      paragraphs: [
        "第三幕结束时，a0 回答“5”，a1 回答“6”；它们的 `status` 都是 `COMPLETED`。这并不是说两份答案都正确，只表示两次生成都以 stop 正常结束。生成怎样停下，由 status 记录；答案究竟好不好，要由 reward 另行判断。",
        "本课把判卷规则刻意做得很简单：回答与参考答案一致，raw reward 记为 1，否则记为 0。于是 a0 的“5”得到 1，a1 的“6”得到 0；另一组里，b0 的“7”得到 1，b1 的“8”得到 0。判分只给原来的 Sample 补上 `reward`，不会改写它的回答、token 或终止状态。",
        "接着 collect 把结果收回。它收的不是一张“高分榜”，而是候选数量齐全的 prompt group：`[a0, a1]` 仍然一起进入 group 0，`[b0, b1]` 仍然一起进入 group 1。这里的“完整”是说每组应有的候选都在，不是说每个候选都答对。",
      ],
      directAnswer:
        "因为 `reward=0` 是一条评价结果，不是删除指令。默认本课路径会保留 a1，并把 a0/a1 作为完整 group 一起交给下一阶段；正是 1 与 0 的差异，让后续组内比较有东西可学。只有显式启用的过滤逻辑才可能舍弃一个 group，而且它与 reward 本身是两回事。",
      evidenceLead: "把“正常结束、判分、收回”分成三个时刻，职责就不会再串在一起。",
      takeaway: "`status` 记录旅程怎样结束，`reward` 记录结果得到怎样的评价，`collect` 决定哪些完整组进入本轮结果。",
    },
    walkthrough: {
      kicker: "本课实例 · 两张答卷、两个动作",
      title: "先判 a0/a1，再把 group 0 原样收回",
      introduction: "只看 group 0 就够了：生成结束不等于判对，reward 为 0 也不等于删除。",
      steps: [
        {
          label: "01 · 生成已结束",
          title: "两份答卷都交上来了",
          body: "a0 与 a1 都正常停止；此刻只知道它们说了什么，还没有评价好坏。",
          facts: [
            "a0 → response \"5\" · COMPLETED",
            "a1 → response \"6\" · COMPLETED",
            "两条 reward 都是 None",
          ],
        },
        {
          label: "02 · Reward 评价",
          title: "逐条对照参考答案“5”",
          body: "教学规则把正确记为 1、错误记为 0；它改变 reward，不改变生成历史。",
          facts: [
            "a0: \"5\" = label \"5\" → reward 1",
            "a1: \"6\" ≠ label \"5\" → reward 0",
            "status 仍都是 COMPLETED",
          ],
        },
        {
          label: "03 · collect 收回",
          title: "整组进入 rollout 结果",
          body: "collect 保留组的边界；低分候选不是垃圾，它是组内比较的另一半。",
          facts: [
            "group 0 = [a0(1), a1(0)]",
            "group 1 = [b0(1), b1(0)]",
            "本课收回 2 个完整 group",
          ],
        },
      ],
      caption: "collect 造成的是容器层面的变化：完整 group 被加入 rollout 结果 `data`；它不会在 Sample 里凭空新增一个 `collected=true` 字段。下一幕才会把这些 raw reward 转成训练侧需要的派生值。",
    },
    fieldChanges: [
      "判分写回原记录：a0/a1 的 `reward: None → 1 / 0`",
      "另一组同样判分：b0/b1 的 `reward: None → 1 / 0`",
      "生成历史保持原样：`response`、`tokens`、`loss_mask`、`status` 不被判分改写",
      "收集保留组边界：`group 0=[a0,a1]`，`group 1=[b0,b1]`",
      "collect 改变的是 rollout 结果容器，不会给 Sample 新增 `collected` 字段",
    ],
    explanation: [
      {
        id: "act-4-fact",
        kind: "source-fact",
        title: "源码先完成生成与 hook，再补 reward",
        body: "默认 `generate_and_rm` 路径先生成 Sample，再运行 sample hooks；如果 Sample 没有被 abort、也尚未自带 reward，才调用 reward function 并把结果写入 `Sample.reward`。随后 `generate_rollout_async` 等待 group 返回，检查组内候选数量，再把整个 group 加入收集结果。",
      },
      {
        id: "act-4-fixture",
        kind: "teaching-fixture",
        title: "这个 1/0 是教学判卷，不是线上 RM 实测",
        body: "fixture 直接固定 a0、b0 的 raw reward 为 1，a1、b1 为 0；四条都保持 `COMPLETED`。这样能先看清数据形状，但不代表真实任务只能做二元评分。生产路径可以调用规则函数、自定义 reward function 或服务；本例没有发送网络 reward 请求。",
      },
      {
        id: "act-4-preview",
        kind: "advanced-preview",
        title: "filter 是收集阶段的一扇可选闸门",
        body: "显式配置 dynamic filter 后，函数会看到一个完整 group，并决定整组 keep / drop；被 drop 的组不计入目标数量，收集循环会继续取新数据。它不是“reward 为 0 就删除该 Sample”的默认规则。partial 模式还可能回收 abort group，本课暂不展开恢复协议。",
      },
    ],
    sourceRefIds: ["rollout.generate-and-rm", "rollout.generate-async"],
    glossaryTermIds: ["raw-reward", "loss-mask", "terminal-status", "dynamic-filter"],
    misconception: {
      belief: "collect 只保留 reward 高的 Sample，所以 a1 与 b1 会在这一幕消失。",
      correction: "默认收集单位是完整 group，而不是单条高分答案。本课保留 a0/a1 与 b0/b1；可选 dynamic filter 也在 group 层明确做 keep / drop，不等于逐条删除零分 Sample。",
    },
    microCheck: {
      prompt: "a0 的 status=COMPLETED、reward=1；a1 的 status=COMPLETED、reward=0。这三个值分别说明什么？",
      answer: "两条生成都正常结束；a0 的结果被判为正确，a1 的结果被判为错误。它们仍属于同一个完整 group。",
      feedback: "status 讲终止方式，reward 讲结果评价；两者都不是 collect 的单条删除开关。",
    },
    transition: "两组答卷已经带着 raw reward 收回，但 Megatron 还不能直接消费这些 Sample；下一幕要跨过显式转换边界。",
  },
  {
    id: "act-5",
    number: 5,
    slug: "conversion-and-schedule",
    title: "第五幕：交接与排程——从 Sample 到 train data",
    shortTitle: "交接与排程",
    durationMinutes: 4,
    drivingQuestion: "哪些值仍属于 raw Sample，哪些是转换、reward 处理和 batch 调度后才出现的派生数据？",
    stage: {
      actor: "RolloutManager",
      visual: "左栏锁定 raw Sample，右栏生成 train_data；Batch 计算器从 4 logical rollouts 推出 2 training steps。",
    },
    fieldChanges: [
      "reward → raw_reward 与 rewards（组内中心化 reward）",
      "index → sample_indices；缺失 rollout_id → 派生 rollout_ids",
      "loss_mask → loss_masks；同一 logical rollout → rollout_mask_sums",
      "4 logical rollouts ÷ global_batch_size 2 = 2 training steps",
    ],
    explanation: [
      {
        id: "act-5-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "RolloutManager 先验证并 flatten rollout 数据，再显式转换字段，最后按 logical rollout 构造 DP schedule。给 Sample 新增字段，不代表 trainer 会自动看到它。",
      },
      {
        id: "act-5-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "本例关闭 std normalization，所以 rewards 只展示 reward 减组均值后的组内中心化 reward：每组为 +0.5/-0.5。它是派生 train data，不写回 Sample.reward。",
      },
      {
        id: "act-5-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "一次逻辑 rollout fan-out 成多个物理训练片段时，同一逻辑 rollout 的派生片段共享 Sample.rollout_id，但每个物理 Sample 的 index 仍不同。默认 fixture 不启用 fan-out。",
      },
    ],
    sourceRefIds: [
      "rollout.manager-generate",
      "rollout.get-data",
      "rollout.post-process-rewards",
      "rollout.convert-train-data",
      "rollout.split-train-data",
      "schedule.build-dp-schedule",
      "test.dp-schedule-contract",
    ],
    glossaryTermIds: [
      "logical-rollout",
      "rollout-id",
      "centered-reward",
      "train-data",
      "rollout-batch",
      "training-step",
    ],
    misconception: {
      belief: "给 Sample 新增字段后，Megatron 会自然看到它。",
      correction: "训练侧需要的新字段必须被 converter 与 per-rank packaging 显式传递。",
    },
    microCheck: {
      prompt: "response_length=3 且 loss_mask=None；若 remove_sample=false/true，转换后的 mask 分别是什么？",
      answer: "false 时为 [1,1,1]；true 时为 [0,0,0]。",
      feedback: "缺失 mask 会按 response 长度补 1；移除训练贡献时再清零。",
    },
    transition: "旅程中的对象已经从 Sample 变成 trainer batch；下一幕用派生训练信号更新 actor。",
  },
  {
    id: "act-6",
    number: 6,
    slug: "training",
    title: "第六幕：训练——Sample 在边界处冻结，actor 参数开始变化",
    shortTitle: "训练",
    durationMinutes: 2.5,
    drivingQuestion: "Megatron 真正消费什么；mask 为 0 的 token 在这里发生什么？",
    stage: {
      actor: "Megatron actor",
      visual: "raw Sample 移入历史区；两个 training step 进入 actor，有效 mask 位置连向 loss 与 optimizer。",
    },
    fieldChanges: [
      "Sample 对象不再修改",
      "per-DP train data 被搬到设备并构造 microbatch schedule",
      "actor 参数从 actor@0 训练到 actor@1，但尚未发布到 SGLang",
    ],
    explanation: [
      {
        id: "act-6-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "actor 训练侧接收 per-DP train data，不接收 Sample dataclass。它基于配置准备 log-prob、advantage / returns 与 loss；有效 response-side mask 决定可贡献的位置。",
      },
      {
        id: "act-6-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "播放器用 actor@0 → actor@1 表示参数更新边界，不模拟真实张量、loss 数值、吞吐或 GPU 时长。",
      },
      {
        id: "act-6-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "PPO、GRPO、GSPO 与 CISPO 在训练信号和 loss 上有不同细节；首课只保留所有算法都必须面对的数据边界。",
      },
    ],
    sourceRefIds: ["actor.consume-rollout-data", "actor.train"],
    glossaryTermIds: ["train-data", "training-step", "loss-mask", "weight-version"],
    misconception: {
      belief: "trainer 会重新检查 prompt group，并根据 group_index 决定 loss。",
      correction: "trainer 看到的是 converter 与 scheduler 交付的字段；分组处理与 logical rollout 归一化信息必须在边界前正确准备。",
    },
    microCheck: {
      prompt: "把 status、rollout_mask_sums、optimizer step 分到 raw Sample、derived train data、actor state 三栏。",
      answer: "status 属于 raw Sample；rollout_mask_sums 属于 derived train data；optimizer step 属于 actor state。",
      feedback: "同一页面可以并排展示三层状态，但不能把它们混成同一个对象。",
    },
    transition: "actor 已更新，rollout engine 却仍可能持有旧权重；下一幕完成显式发布边界。",
  },
  {
    id: "act-7",
    number: 7,
    slug: "weight-return",
    title: "第七幕：权重回流——闭环真正闭合",
    shortTitle: "权重回流",
    durationMinutes: 2.5,
    drivingQuestion: "optimizer step 完成后，为什么不能假设下一次 SGLang generation 已经使用新 actor？",
    stage: {
      actor: "Weight sync",
      visual: "Actor 显示 actor@1/unpublished；同步完成后 SGLang 才从 actor@0 切到 actor@1，历史卡片保持不变。",
    },
    fieldChanges: [
      "Megatron actor: actor@0 → actor@1",
      "SGLang engine: actor@0 → actor@1（显式同步完成后）",
      "历史 Sample.weight_versions 保持 actor@0",
      "下一轮 Sample 才记录 actor@1",
    ],
    explanation: [
      {
        id: "act-7-fact",
        kind: "source-fact",
        title: "源码事实",
        body: "默认同步循环在当前训练后显式调用 actor_model.update_weights，再进入下一次 generation。同步改变 rollout engine 的系统状态，不回写历史 Sample。",
      },
      {
        id: "act-7-fixture",
        kind: "teaching-fixture",
        title: "教学 fixture",
        body: "actor@0/actor@1 和时间块宽度用于表达版本与相对顺序，不是实际 checkpoint 名、transport trace 或性能 benchmark。",
      },
      {
        id: "act-7-preview",
        kind: "advanced-preview",
        title: "进阶预告",
        body: "async 可以让 rollout(i+1) 与 train(i) 重叠，因此它可能仍由 actor@i 生成；发布前会等待进行中的 generation，避免请求中途切换权重。",
      },
    ],
    sourceRefIds: ["loop.sync", "loop.async", "actor.update-weights"],
    glossaryTermIds: ["weight-version", "weight-sync", "asynchronous-rollout"],
    misconception: {
      belief: "optimizer step 一结束，正在生成的所有请求会自然切到新权重。",
      correction: "权重发布是显式系统边界；异步路径还会先让重叠中的 generation 完成，再发布新版本。",
    },
    microCheck: {
      prompt: "异步时间线中的 rollout(i+1) 为什么可能仍记录 actor@i？",
      answer: "它与 train(i) 重叠，在新权重发布前已经开始；发布边界会先等待进行中的 generation。",
      feedback: "异步改变重叠关系，不取消一致的权重发布边界。",
    },
    transition: "闭环完成：下一条 Sample 会记录新 policy 做了什么，而历史 Sample 继续保留生成当时的版本。",
  },
];

export const sampleJourneyAssessment = {
  id: "core.sample-journey.check",
  version: 1,
  title: "章末知识检查",
  description: "可无限重试。至少答对 7 题，并且 q4、q5、q8 必须正确。",
  questions: [
    {
      id: "q1",
      type: "ordering",
      prompt: "把一条 Sample 的七段闭环按发生顺序排列。",
      options: [
        { id: "dataset", label: "Dataset 构造初始 Sample" },
        { id: "group", label: "DataSource 建立同组候选" },
        { id: "generate", label: "SGLang 生成 response" },
        { id: "reward", label: "Reward 逐条评分，collect 按组收回" },
        { id: "convert", label: "RolloutManager 转换与排程" },
        { id: "train", label: "Megatron actor 训练" },
        { id: "sync", label: "weight sync 发布新权重" },
      ],
      correctOrder: ["dataset", "group", "generate", "reward", "convert", "train", "sync"],
      required: false,
      answerSummary: "Dataset → 分组 → 生成 → Reward 评分 → collect 按组收回 → 转换/排程 → train → weight sync。",
      feedback: {
        correct: "顺序正确。你已经能复原闭环骨架。",
        incorrect: "先只追踪交接关系，不要把字段细节混进顺序。回看 90 秒闭环。",
      },
      returnTo: { label: "回看 90 秒闭环", href: "/learn/sample-journey#overview" },
    },
    {
      id: "q2",
      type: "multiple",
      prompt: "关于刚由 Dataset 构造出的初始 Sample，哪些说法正确？",
      options: [
        { id: "semantic", label: "已经有 prompt、label 与 metadata" },
        { id: "pending", label: "status 为 PENDING" },
        { id: "empty", label: "tokens 与 response 仍为空" },
        { id: "rewarded", label: "已经有组内中心化 reward" },
        { id: "tensor", label: "已经是 Megatron tensor batch" },
      ],
      correctOptionIds: ["semantic", "pending", "empty"],
      required: false,
      answerSummary: "初始 Sample 保存语义输入，生成与训练侧字段仍未准备。",
      feedback: {
        correct: "正确。Sample 已出生，但还没有经过生成、评价与转换。",
        incorrect: "注意时间点：Dataset 只完成了 Sample 的初始语义字段。",
      },
      returnTo: { label: "回到第一幕", href: "/learn/sample-journey#act-1", actId: "act-1" },
    },
    {
      id: "q3",
      type: "single",
      prompt: "3 个 prompts、每个 prompt 生成 N=4 个同组候选，会得到多少 group 与物理 Sample？",
      options: [
        { id: "3-12", label: "3 个 group，12 条 Sample" },
        { id: "12-12", label: "12 个 group，12 条 Sample" },
        { id: "3-4", label: "3 个 group，4 条 Sample" },
        { id: "4-12", label: "4 个 group，12 条 Sample" },
      ],
      correctOptionIds: ["3-12"],
      required: false,
      answerSummary: "prompt 数决定 group 数；每组 N 个候选，所以 3×4=12 条 Sample。",
      feedback: {
        correct: "正确。同组 group_index 相同，但物理 index 各不相同。",
        incorrect: "不要把候选数当成 group 数：一个 prompt 对应一个 group。",
      },
      returnTo: { label: "回到第二幕", href: "/learn/sample-journey#act-2", actId: "act-2" },
    },
    {
      id: "q4",
      type: "single",
      prompt: "prompt 有 6 个 token、response 有 4 个 token。哪组长度关系正确？",
      options: [
        { id: "10-4-4", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=4" },
        { id: "10-10-4", label: "len(tokens)=10，response_length=10，len(rollout_log_probs)=4" },
        { id: "6-4-10", label: "len(tokens)=6，response_length=4，len(rollout_log_probs)=10" },
        { id: "10-4-10", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=10" },
      ],
      correctOptionIds: ["10-4-4"],
      required: true,
      answerSummary: "tokens 包含 prompt 前缀和 response 后缀；response 元数据只在 response 空间对齐。",
      feedback: {
        correct: "关键不变量正确。",
        incorrect: "这是一道必对题：把完整 tokens 与 response-side 元数据分开计算。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q5",
      type: "single",
      prompt: "response 依次包含 2 个模型 token、2 个工具 token、3 个模型 token。正确 mask 与有效长度是什么？",
      options: [
        { id: "mask-correct", label: "[1,1,0,0,1,1,1]，有效长度 5" },
        { id: "mask-all", label: "[1,1,1,1,1,1,1]，有效长度 7" },
        { id: "mask-tool", label: "[0,0,1,1,0,0,0]，有效长度 2" },
        { id: "mask-short", label: "[1,1,1,1,1]，有效长度 5" },
      ],
      correctOptionIds: ["mask-correct"],
      required: true,
      answerSummary: "模型动作位置为 1，工具 observation 位置为 0；mask 仍与全部 response 位置等长。",
      feedback: {
        correct: "关键 mask 对齐正确。",
        incorrect: "这是一道必对题：工具 token 仍占 response 位置，但不贡献训练 mask。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q6",
      type: "single",
      prompt: "finish reason 与 terminal status 的正确映射是哪一项？",
      options: [
        { id: "correct", label: "stop→COMPLETED，length→TRUNCATED，abort→ABORTED" },
        { id: "swap", label: "stop→TRUNCATED，length→COMPLETED，abort→ABORTED" },
        { id: "all", label: "三者都映射为 COMPLETED" },
        { id: "pending", label: "三者都保持 PENDING" },
      ],
      correctOptionIds: ["correct"],
      required: false,
      answerSummary: "stop、length、abort 分别映射为 COMPLETED、TRUNCATED、ABORTED。",
      feedback: {
        correct: "正确。status 描述生成如何结束。",
        incorrect: "回看生成终止阶段，不要把 reward 与 terminal status 混淆。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q7",
      type: "multiple",
      prompt: "下面哪些值不是 raw Sample 字段，而是在转换后才出现的 derived train data？",
      options: [
        { id: "centered", label: "组内中心化 reward" },
        { id: "mask-sum", label: "rollout_mask_sums" },
        { id: "status", label: "terminal status" },
        { id: "prompt", label: "prompt" },
      ],
      correctOptionIds: ["centered", "mask-sum"],
      required: false,
      answerSummary: "组内中心化 reward 与 rollout_mask_sums 都在 Sample→train data 边界派生。",
      feedback: {
        correct: "正确。你没有把派生训练数据伪装成 Sample 字段。",
        incorrect: "锁定 raw Sample 与 derived train data 两栏，再看字段从哪里出现。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q8",
      type: "single",
      prompt: "一次逻辑 rollout fan-out 成多个训练片段时，为什么它们共享 rollout_id、却拥有不同 index？",
      options: [
        {
          id: "identity-correct",
          label: "rollout_id 标记同一逻辑执行，index 标记各物理 Sample，避免重复计数又保留独立身份",
        },
        { id: "duplicate", label: "它们其实是完全相同的重复对象，所以两个 ID 都应该相同" },
        { id: "group", label: "rollout_id 等同于 prompt group 的 group_index" },
        { id: "random", label: "两种 ID 都只是随机展示值，下游不使用" },
      ],
      correctOptionIds: ["identity-correct"],
      required: true,
      answerSummary: "rollout_id 聚合逻辑执行；index 保持每个物理训练片段的唯一身份。",
      feedback: {
        correct: "关键身份边界正确。",
        incorrect: "这是一道必对题：不要把 prompt group、逻辑 rollout 与物理 Sample 合并。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q9",
      type: "single",
      prompt: "异步路径中的 rollout(i+1) 为什么可能仍使用 actor@i？",
      options: [
        { id: "overlap", label: "它与 train(i) 重叠并在新权重发布前开始；发布前会等待进行中的 generation" },
        { id: "rewrite", label: "新权重会在完成后回写历史 Sample，所以版本无所谓" },
        { id: "no-sync", label: "异步路径永远不做 weight sync" },
        { id: "mid-request", label: "请求进行到一半时会无条件切到 actor@i+1" },
      ],
      correctOptionIds: ["overlap"],
      required: false,
      answerSummary: "生成与训练可以重叠，但显式发布边界仍要等待进行中的 generation，避免请求中途混用版本。",
      feedback: {
        correct: "正确。异步改变时间重叠，不取消版本边界。",
        incorrect: "对照 sync/async 时间线，找到 generation、train 与 weight barrier 的相对位置。",
      },
      returnTo: { label: "回到第七幕", href: "/learn/sample-journey#act-7", actId: "act-7" },
    },
  ] satisfies AssessmentQuestion[],
  completion: {
    minCorrect: 7,
    requiredQuestionIds: ["q4", "q5", "q8"],
    requiredActIds: ["act-1", "act-2", "act-3", "act-4", "act-5", "act-6", "act-7"],
    unlimitedRetries: true,
    progressScope: "device-local",
  },
} as const;

export const sampleJourneyLesson = {
  metadata: {
    schemaVersion: 1,
    id: "core.sample-journey",
    kind: "lesson",
    locale: "zh-CN",
    route: "/learn/sample-journey",
    title: "一条 Sample 的旅程",
    summary:
      "一行数据刚进入 slime 时，还只带着一道题。接下来的七幕里，我们会看着它得到回答、评分与训练信号，最终推动一次权重更新，再把更新后的权重发布给下一轮生成。",
    audiences: ["researcher", "engineer"],
    level: "slime-intro",
    duration: { minMinutes: 25, maxMinutes: 30, includesAssessment: true },
    workflowStatus: "ready",
    freshnessStatus: "current",
    visibility: "public",
    lessonRevision: 4,
    prerequisites: ["concept.rl-loop-basics"],
    learningObjectives: [
      "按顺序复述 Dataset → DataSource → SGLang → Reward → collect → train data → Megatron → weight sync 闭环。",
      "区分 dataset row、prompt group、物理 Sample、逻辑 rollout、rollout batch 与 training step。",
      "解释 tokens、response_length、loss_mask、rollout_log_probs、reward 与 status 的边界。",
      "检查 response 侧长度、逻辑身份与 batch 守恒三个关键不变量。",
      "指出 optimizer step 与权重发布的边界，并对比同步与异步的最小差异。",
    ],
    learningObjectiveIds: [
      "sample-lifecycle",
      "token-alignment",
      "identity-boundaries",
      "batch-conservation",
      "weight-publication-boundary",
    ],
    completion: {
      assessmentId: "core.sample-journey.check",
      assessmentVersion: 1,
      minCorrect: 7,
      requiredQuestionIds: ["q4", "q5", "q8"],
      requiredActs: [1, 2, 3, 4, 5, 6, 7],
    },
    baseline: {
      repository: "THUDM/slime",
      nearestTag: "v0.3.1",
      describe: "v0.3.1-1-g06ffdbe2",
      commit: "06ffdbe22be068b52f9ed0fc318c473f7030197e",
    },
    fixtureIds: ["math-2x2-v1"],
    glossaryTermIds: [
      "dataset-row",
      "sample-object",
      "prompt-group",
      "group-index",
      "sample-index",
      "logical-rollout",
      "rollout-id",
      "rollout-batch",
      "training-step",
      "response-length",
      "loss-mask",
      "rollout-log-prob",
      "raw-reward",
      "dynamic-filter",
      "centered-reward",
      "train-data",
      "terminal-status",
      "weight-version",
      "weight-sync",
      "asynchronous-rollout",
    ],
    sourceRefIds: [
      "sample.dataclass",
      "dataset.construct-sample",
      "rollout.datasource-get-samples",
      "sample.append-response-tokens",
      "rollout.convert-train-data",
      "schedule.build-dp-schedule",
      "actor.train",
      "actor.update-weights",
    ],
    testRefIds: ["test.sample-contract", "test.dp-schedule-contract"],
    owners: {
      content: "project-initiator",
      technicalReview: "project-initiator-or-designated-slime-reviewer",
    },
  },
  opening: {
    eyebrow: "序章 · 一条记录出发",
    title: "它最初只是一道题。",
    paragraphs: [
      "此刻还没有回答，没有分数，也没有训练信号。它只是数据集里安静的一行，等待系统把它读进来。",
      "接下来，它会被复制成同组候选，交给模型生成答案，接受评价，再被整理成训练能够理解的形状。每越过一个系统边界，它都会多出一些字段，也多承担一层含义。",
      "到了第六幕，优化器终于根据派生训练数据完成一次更新；第七幕再把新权重发布给 rollout engine。至此，下一轮生成才真正有了新的起点。",
    ],
    closing: "先别急着记字段。先看它走完全程。",
    coverKicker: "序章 / 一条记录出发",
    coverCaption: "一道题，走向权重更新。",
    overviewKicker: "90 秒 · 技术速览",
  },
  hook: {
    question: "同样答对，为什么一个 Sample 完全不学习？",
    sampleA: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[1])',
    sampleB: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[0])',
    resolution:
      "reward 评价结果；loss_mask 决定 response 中哪些 token 能参与优化。B 没有有效训练 token。",
    revealAfterActId: "act-5",
  },
  invariants: [
    "tokens = prompt token 前缀 + response token 后缀",
    "loss_mask 存在时：len(loss_mask) == response_length",
    "rollout_log_probs 存在时：len(rollout_log_probs) == response_length",
    "一次逻辑 rollout 的派生片段共享 Sample.rollout_id；每个物理 Sample 的 index 仍不同",
  ],
  overview90s: sampleJourneyOverview,
  acts: sampleJourneyActs,
  assessment: sampleJourneyAssessment,
  closingMemory:
    "Sample 记录模型在某个 policy 版本下做了什么；train data 规定 trainer 怎样聚合它；weight sync 决定下一条 Sample 由哪个 policy 产生。",
  scopeNotice: {
    sourceFact: "带“源码事实”的结论已对照固定 commit 06ffdbe2。",
    teachingFixture: "带“教学 fixture”的数值只用于稳定讲解，不是实测 trace 或性能 benchmark。",
    advancedPreview: "带“进阶预告”的内容只标出下一步，不作为本课完成要求。",
  },
} as const;
