import type { AssessmentQuestion, LessonAct, OverviewStep } from "../types";

export const sampleJourneyOverview = {
  title: "先建立完整闭环",
  description: "这份 90 秒概览只回答三个问题：每个组件接收什么、产生什么，以及把结果交给谁。字段与源码将在对应幕展开。",
  totalSeconds: 90,
  steps: [
    {
      id: "overview-dataset",
      order: 1,
      actor: "Dataset",
      action: "把输入行构造成尚未完成的 Sample",
      passesTo: "DataSource",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-group",
      order: 2,
      actor: "DataSource",
      action: "复制 prompt，建立同组候选与独立身份",
      passesTo: "SGLang",
      durationSeconds: 12,
      kind: "source-fact",
    },
    {
      id: "overview-generate",
      order: 3,
      actor: "SGLang",
      action: "生成 response，补齐 token、mask、log-prob 与状态",
      passesTo: "Reward → collect",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-reward",
      order: 4,
      actor: "Reward → collect",
      action: "逐条评价结果，再按完整 group 收回",
      passesTo: "RolloutManager",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-convert",
      order: 5,
      actor: "RolloutManager",
      action: "把 Sample 显式转换、排程为 trainer batch",
      passesTo: "Megatron actor",
      durationSeconds: 14,
      kind: "source-fact",
    },
    {
      id: "overview-train",
      order: 6,
      actor: "Megatron actor",
      action: "消费派生训练数据，执行 optimizer step",
      passesTo: "Weight sync",
      durationSeconds: 13,
      kind: "source-fact",
    },
    {
      id: "overview-sync",
      order: 7,
      actor: "Weight sync",
      action: "把新 actor 权重发布给 rollout engine",
      passesTo: "下一轮 DataSource",
      durationSeconds: 13,
      kind: "source-fact",
    },
  ] satisfies OverviewStep[],
} as const;

export const sampleJourneyActs: LessonAct[] = [
  {
    id: "act-1",
    number: 1,
    slug: "birth",
    title: "第一幕：构造——从外部记录到 Sample",
    shortTitle: "构造",
    durationMinutes: 2,
    drivingQuestion: "这行数据刚进入 slime，就已经变成模型能训练的张量了吗？",
    stage: {
      actor: "Dataset → Sample",
      visual: "本幕只检查 Dataset 的输出边界：哪些字段在构造 Sample 时确定，哪些字段必须由后续阶段产生。",
    },
    prediction: {
      prompt: "Dataset 刚完成构造。下面哪一组状态最可能属于此刻的 Sample？",
      options: [
        { id: "semantic-only", label: "已有 prompt、label、metadata；tokens 为空，reward 为 None" },
        { id: "generated", label: "已有 response、rollout_log_probs 与 reward" },
        { id: "train-batch", label: "已经变成 Megatron 可直接消费的 tensor batch" },
      ],
      correctOptionId: "semantic-only",
      feedback: {
        correct: "正确。Dataset 只完成框架内部表示的初始构造。",
        incorrect: "先区分“构造 Sample”和“产生训练数据”：生成与训练字段要在后续边界出现。",
      },
    },
    narrative: {
      kicker: "默认数据路径 · 构造边界",
      title: "Sample 是统一中间表示，不是训练 batch。",
      paragraphs: [
        "Dataset 从 JSONL 或 Parquet 读取一条外部记录后，先将语义输入映射到框架内部统一的 `Sample` 结构。默认路径在这里写入 `prompt`、`label` 与 `metadata`，但不执行模型生成，也不构造 Megatron 的训练张量。",
        "因此，初始 `Sample` 的生成与训练字段仍处于未产生状态：`tokens=[]`、`response=\"\"`、`reward=None`、`loss_mask=None`，生命周期状态为 `PENDING`。这些空值不是异常，而是当前系统边界的预期输出。",
      ],
      directAnswer:
        "没有。默认教学路径此时只把 `text`、`label` 和 `metadata` 放进 `Sample`；`tokens` 仍是空列表，`reward` 与 `loss_mask` 仍是 `None`，更没有 trainer 能直接使用的 tensor batch。",
      evidenceLead: "下面用字段快照和固定源码锚点验证这一构造边界。",
      takeaway: "`PENDING` 表示 Sample 已构造、生成尚未开始；它不是失败状态。",
    },
    fieldChanges: [
      "题目进入档案：`row.text → Sample.prompt`",
      "参考答案与来源被保留：`row.label / metadata → Sample.label / metadata`",
      "模型尚未回答：`tokens=[]`、`response=\"\"`、`response_length=0`",
      "评价尚未发生：`reward=None`、`loss_mask=None`",
      "生命周期刚刚开始：`status=PENDING`",
    ],
    explanation: [
      {
        id: "act-1-fact",
        kind: "source-fact",
        title: "源码边界：Dataset 只构造初始 Sample",
        body: "源码先从 JSONL 或 Parquet 读出一行，再取出 prompt、label 与 metadata，调用 `Sample(...)` 构造框架内对象。这一步保存的是语义输入，不是 Megatron 可直接消费的训练张量。",
      },
      {
        id: "act-1-fixture",
        kind: "teaching-fixture",
        title: "教学范围：固定两道题并关闭 chat template",
        body: "教学 fixture 只包含两道算术题，并关闭 chat template，以隔离 `Sample` 构造这一变量。这不表示 slime 仅支持简单文本，也不代表生产数据路径必须使用相同配置。",
      },
      {
        id: "act-1-preview",
        kind: "advanced-preview",
        title: "扩展范围：工具、多模态与 chat template",
        body: "真实任务可以在 metadata 中携带 tools，也可以包含多模态字段或应用 chat template。输入形式可以扩展，但本幕的系统边界不变：Dataset 构造初始 `Sample`，而不是最终训练 batch。",
      },
    ],
    sourceRefIds: ["dataset.read-file", "dataset.construct-sample", "sample.dataclass"],
    glossaryTermIds: ["dataset-row", "sample-object", "terminal-status"],
    misconception: {
      belief: "只要数据行进入框架，token、mask 和训练张量就都准备好了。",
      correction:
        "没有。默认路径在这一幕不会把 token ID 写入 `Sample.tokens`，`loss_mask` 也尚未产生；即使启用长度过滤时会借助 tokenizer 检查长度，这仍不等于构造训练张量。",
    },
    microCheck: {
      prompt: "此刻的 Sample 已经拥有什么，又还缺什么？",
      answer:
        "已有 `prompt`、`label` 与 `metadata`；`tokens=[]`、`reward=None`、`loss_mask=None`，`status=PENDING`。",
      feedback: "它已经是框架内的 `Sample`，却还不是 trainer 能消费的训练数据。",
    },
    transition: "初始 Sample 已经构造完成。下一幕解释 DataSource 为什么要为同一 prompt 建立多个独立候选。",
  },
  {
    id: "act-2",
    number: 2,
    slug: "grouping",
    title: "第二幕：分组——建立可比较的独立候选",
    shortTitle: "分组",
    durationMinutes: 2.5,
    drivingQuestion: "为什么同一道题要复制两份？复制后，哪些相同，哪些必须不同？",
    stage: {
      actor: "DataSource",
      visual: "以 `3 + 2 = ?` 为例，检查 DataSource 如何构造 a0 与 a1，以及 `group_index` 和 `index` 分别表达什么。",
    },
    prediction: {
      prompt: "输入 3 个 prompt，每个 prompt 生成 4 个候选。DataSource 应输出什么？",
      options: [
        { id: "three-twelve", label: "3 个 group、12 条物理 Sample" },
        { id: "twelve-twelve", label: "12 个 group、12 条物理 Sample" },
        { id: "three-four", label: "3 个 group、4 条物理 Sample" },
      ],
      correctOptionId: "three-twelve",
      feedback: {
        correct: "正确。prompt 数决定 group 数，候选数决定每组的物理 Sample 数。",
        incorrect: "先固定一个 prompt 对应一个比较组，再乘以每组候选数。",
      },
    },
    narrative: {
      kicker: "采样结构 · 共享条件与独立身份",
      title: "DataSource 为同一 prompt 构造 N 个独立候选。",
      paragraphs: [
        "同一 prompt 的单次生成不足以形成组内比较。DataSource 因此按照 `n_samples_per_prompt` 深拷贝初始 Sample；本教学配置取 N=2，于是 `3 + 2 = ?` 产生候选 a0 与 a1。复制的目的不是简单增加记录数量，而是在相同输入条件下获得多个独立 rollout。",
        "a0 与 a1 共享相同的 `prompt`、`label`、`metadata` 内容和 `group_index=0`，因为后续需要把它们作为同一比较组处理；二者拥有不同的 `index`，因为每次生成都必须可独立追踪。深拷贝还保证可变字段不发生对象别名。",
      ],
      directAnswer:
        "同组候选共享 `prompt`、`label`、`metadata` 内容与 `group_index`，但必须拥有不同的 `index`。`group_index` 定义比较集合，`index` 标识具体物理 Sample。",
      evidenceLead: "下面把复制、分组与编号对应到 DataSource 的实际调用顺序。",
      takeaway: "共享 `group_index` 建立比较关系；唯一 `index` 保持每次生成的独立身份。",
    },
    walkthrough: {
      kicker: "教学 fixture · group 0",
      title: "从一个 prompt 构造两个独立 Sample",
      introduction: "实例依次展示输入状态、深拷贝与编号，以及 DataSource 的分组输出。",
      steps: [
        {
          label: "01 · 进入 DataSource",
          title: "输入是一个未分组 Sample",
          body: "Sample 已保存语义输入，但 `group_index` 与 `index` 尚未分配，生成也尚未开始。",
          facts: [
            "prompt = \"3 + 2 = ?\"",
            "group_index = None",
            "index = None",
          ],
        },
        {
          label: "02 · 复制并编号",
          title: "深拷贝并分配身份",
          body: "DataSource 使用 `deepcopy` 构造两个对象独立的候选，并分别写入组号与记录号。",
          facts: [
            "n_samples_per_prompt = 2",
            "deepcopy(prompt_sample)",
            "返回形状 = list[group][sample]",
          ],
        },
        {
          label: "03 · 离开 DataSource",
          title: "输出保持组关系与个体身份",
          body: "a0 与 a1 共享比较条件，但后续分别生成并记录各自的 response。",
          facts: [
            "a0 → group_index 0 · index 0",
            "a1 → group_index 0 · index 1",
            "response 仍为空",
          ],
        },
      ],
      caption: "第二道题 `4 + 3 = ?` 同理形成 group 1：b0 的 index 为 2，b1 的 index 为 3。本 fixture 因而得到 2 组、4 条 Sample。",
    },
    fieldChanges: [
      "一条 prompt 变成两个候选：`n_samples_per_prompt=2`",
      "同组标记被写入：a0 与 a1 的 `group_index=0`",
      "独立身份被写入：a0 的 `index=0`，a1 的 `index=1`",
      "题目内容不变，生成仍未开始：两条 `response` 都是空字符串",
      "普通路径此时仍未产生 `Sample.rollout_id`",
    ],
    explanation: [
      {
        id: "act-2-fact",
        kind: "source-fact",
        title: "源码路径：深拷贝、编号、按组返回",
        body: "`RolloutDataSource.get_samples` 逐条取出 `prompt_sample`，在循环中调用 `deepcopy`，给副本写入 `group_index` 与递增的 `index`，再把同组副本装进一个列表。外层列表装 group，内层列表装该 prompt 的候选。",
      },
      {
        id: "act-2-fixture",
        kind: "teaching-fixture",
        title: "教学配置：2 个 prompt × 2 个候选",
        body: "教学 fixture 设置 `rollout_batch_size=2`，所以一次取两道 prompt；又设置 `n_samples_per_prompt=2`，所以每道题各有两个候选。结果是 2 个 group、4 条 Sample：a0/a1 与 b0/b1。a0 这类 ID 只为稳定演示，生产源码真正分配的是数值 `group_index` 与 `index`。",
      },
      {
        id: "act-2-preview",
        kind: "advanced-preview",
        title: "扩展边界：对象独立性与 partial rollout",
        body: "深拷贝使候选内容相同但可变字段对象彼此独立，因此修改 a0 的 metadata 不会影响 a1。partial rollout 还可以让可恢复 group 重新入队；本幕只要求掌握“同组不等于同一实例”。",
      },
    ],
    sourceRefIds: ["rollout.datasource-get-samples"],
    glossaryTermIds: ["prompt-group", "group-index", "sample-index"],
    misconception: {
      belief: "a0 和 a1 的题目完全一样，所以它们就是两份无意义的重复数据。",
      correction: "题目相同正是为了形成可比较的候选；两条记录会分别生成、分别记录 log-prob、分别得到 reward，因此必须有不同 `index`。",
    },
    microCheck: {
      prompt: "3 个 prompts、每个 prompt 生成 4 个候选，会得到多少 group 和 Sample？",
      answer: "3 个 group、12 条 Sample；组内 group_index 相同，所有 index 不同。",
      feedback: "prompt 数决定 group 数；每组候选数再决定物理 Sample 总数。",
    },
    transition: "身份已经建立，但这些同组候选仍是空白；现在 SGLang 要为它们各自生成 response。",
  },
  {
    id: "act-3",
    number: 3,
    slug: "generation",
    title: "第三幕：生成——写回 response 与生成证据",
    shortTitle: "生成",
    durationMinutes: 4,
    drivingQuestion: "SGLang 只回答了一个“5”，为什么 Sample 里却同时多出这么多字段？",
    stage: {
      actor: "SGLang",
      visual: "只跟随 a0，检查请求准备、response token 写回、数组对齐、终止状态与权重版本。",
    },
    prediction: {
      prompt: "请求已有 5 个 prompt token，SGLang 接着生成 1 个 response token。写回后哪组长度正确？",
      options: [
        { id: "six-one-one", label: "len(tokens)=6，response_length=1，len(loss_mask)=1" },
        { id: "six-six-six", label: "len(tokens)=6，response_length=6，len(loss_mask)=6" },
        { id: "five-one-six", label: "len(tokens)=5，response_length=1，len(loss_mask)=6" },
      ],
      correctOptionId: "six-one-one",
      feedback: {
        correct: "正确。tokens 包含输入前缀与回答后缀，response 元数据只在回答空间对齐。",
        incorrect: "不要把完整 token 序列与 response-side 元数据放进同一个坐标系。",
      },
    },
    narrative: {
      kicker: "生成边界 · 结果与证据",
      title: "一次生成必须同时保存结果、对齐信息与版本来源。",
      paragraphs: [
        "生成路径首先准备 prompt token IDs，并为请求记录 `session_id`。在本教学 fixture 中，`3 + 2 = ?` 被固定表示为 5 个 prompt token；这些 token 只构成输入前缀，`response_length` 此时仍为 0。",
        "SGLang 随后使用 `actor@0` 生成 token 25，解码结果为“5”。`append_response_tokens` 将该 token 追加到 prompt 后，因此 `tokens` 的长度从 5 变为 6；`response_length` 只统计 response 空间，所以值为 1。",
        "生成路径还必须保存后续训练与审计所需的证据：`loss_mask` 标识 response 位置是否参与训练，`rollout_log_probs` 记录生成时 policy 的动作概率，finish reason 映射为 terminal status，`weight_versions` 记录生成所使用的参数版本。",
      ],
      directAnswer:
        "因为训练需要的不只是“模型说了什么”，还要知道“它生成了哪些 token、当时给这些动作多大概率、哪些位置可以训练、生成怎样结束、使用的是哪一版权重”。`response` 保存可读答案，其余字段保存可对齐、可追溯的生成证据。",
      evidenceLead: "下面按请求前、请求准备完成和生成完成三个状态检查字段变化。",
      takeaway: "`response` 保存生成结果；token、mask、log-prob、status 与权重版本保存可训练、可追溯的生成证据。",
    },
    walkthrough: {
      kicker: "教学 fixture · a0",
      title: "response 写回过程的三个状态",
      introduction: "按时间顺序比较请求前、请求准备完成与生成结束时的字段快照。",
      steps: [
        {
          label: "01 · 请求前",
          title: "生成尚未开始",
          body: "a0 已经拥有组号和身份，但它仍处于等待生成的 PENDING 状态。",
          facts: [
            "prompt = \"3 + 2 = ?\"",
            "tokens = []",
            "response = \"\"",
          ],
        },
        {
          label: "02 · 准备 SGLang 请求",
          title: "构造 prompt token 前缀",
          body: "生成路径准备输入 token；session 用来标识或路由这次请求，本课值是固定的教学数据。",
          facts: [
            "session_id = session-a0",
            "tokens = [11, 12, 13, 14, 15]",
            "response_length = 0",
          ],
        },
        {
          label: "03 · 回答并结束",
          title: "追加 response token 并记录元信息",
          body: "SGLang 返回 token 25，也就是“5”；Sample 同步保存动作概率、训练掩码和终止信息。",
          facts: [
            "tokens = [11, 12, 13, 14, 15, 25]",
            "response = \"5\" · response_length = 1",
            "loss_mask = [1] · log_probs = [-0.08]",
            "status = COMPLETED · actor@0",
          ],
        },
      ],
      caption: "关键对齐关系：`tokens` 保存 prompt + response，所以长度是 6；`response_length`、`loss_mask` 与 `rollout_log_probs` 仅对齐 response 空间，所以长度都是 1。",
    },
    fieldChanges: [
      "请求获得身份：`session_id: None → session-a0`",
      "输入先成为 token 前缀：`tokens: [] → [11, 12, 13, 14, 15]`",
      "回答 token 接在末尾：`tokens → [11, 12, 13, 14, 15, 25]`",
      "可读答案被写回：`response: \"\" → \"5\"`，`response_length: 0 → 1`",
      "回答位置获得训练账本：`loss_mask=[1]`，`rollout_log_probs=[-0.08]`",
      "这次生成封存为历史：`status=COMPLETED`，`weight_versions=[actor@0]`",
    ],
    explanation: [
      {
        id: "act-3-fact",
        kind: "source-fact",
        title: "源码路径：准备请求、调用 SGLang、写回 Sample",
        body: "`generate` 先准备 prompt IDs，再把请求发给 SGLang；响应回来后，`append_response_tokens` 把新 token 接到 `Sample.tokens`，同时更新 `response`、`response_length`、`loss_mask` 与 `rollout_log_probs`。最后，meta info 中的 finish reason 被映射为 terminal status。",
      },
      {
        id: "act-3-fixture",
        kind: "teaching-fixture",
        title: "教学配置：固定 token、session 与 log-prob",
        body: "a0 在 fixture 中固定使用 5 个 prompt token 和 1 个 response token；回答 token 25 解码为“5”，对应 rollout log-prob 为 -0.08，生成权重版本为 actor@0。token ID 与 `session-a0` 是为了稳定回放而固定的值，不是线上 tokenizer 或 SGLang 服务的实测输出。",
      },
      {
        id: "act-3-preview",
        kind: "advanced-preview",
        title: "扩展边界：工具 observation 与 streaming",
        body: "本例只有一个模型动作，因此 `loss_mask=[1]` 很直观。agent 场景还会把工具或环境 observation token 接进 response 空间；这些位置可以用 mask 0 与占位 log-prob 表示。播放器只是确定性教学回放，不承诺生产请求一定按相同粒度 streaming。",
      },
    ],
    sourceRefIds: [
      "rollout.generate",
      "sample.append-response-tokens",
      "sample.apply-meta-info",
      "test.sample-status",
      "test.sample-weight-version",
    ],
    glossaryTermIds: ["response-length", "loss-mask", "rollout-log-prob", "weight-version", "terminal-status"],
    misconception: {
      belief: "`tokens` 有 6 项，所以 `loss_mask` 和 `rollout_log_probs` 也应该有 6 项。",
      correction: "`tokens` 包含 5 个 prompt token 与 1 个 response token；Sample 中的 `loss_mask` 和 `rollout_log_probs` 只描述 response 空间，所以各有 1 项。训练数据层随后才把 mask 对齐到完整序列。",
    },
    microCheck: {
      prompt: "5 个 prompt token，加上 2 个模型、2 个工具、1 个模型 token：三个长度是多少？",
      answer: "len(tokens)=10，response_length=5，len(loss_mask)=len(rollout_log_probs)=5；有效 response 长度为 3。",
      feedback: "prompt 前缀只计入 tokens；mask 与 rollout log-prob 在 response 空间对齐。",
    },
    transition: "生成结果及其证据已经写回 Sample。下一幕区分 terminal status、reward 与 collect 的职责。",
  },
  {
    id: "act-4",
    number: 4,
    slug: "reward-and-collect",
    title: "第四幕：评价与收集——区分 status、reward 与 group 完整性",
    shortTitle: "评价与收集",
    durationMinutes: 2.5,
    drivingQuestion: "a1 的 reward 是 0，为什么 collect 没有把它丢掉？",
    stage: {
      actor: "Reward → collect",
      visual: "先对四条 response 逐条计算 reward，再检查 collect 为什么按完整 group 返回结果。",
    },
    prediction: {
      prompt: "a0 与 a1 都正常结束，但 a1 的 reward 是 0。默认 collect 下一步会怎样处理？",
      options: [
        { id: "keep-group", label: "保留 a0/a1，按完整 group 交给下一阶段" },
        { id: "drop-zero", label: "立即删除 a1，只留下高分 Sample" },
        { id: "abort-group", label: "把整个 group 标记为 ABORTED" },
      ],
      correctOptionId: "keep-group",
      feedback: {
        correct: "正确。reward 是评价结果，不是默认删除指令。",
        incorrect: "先把 status、reward 和 collect 的职责拆开：三者回答不同问题。",
      },
    },
    narrative: {
      kicker: "评价边界 · 三种不同语义",
      title: "status、reward 与 collect 回答三个不同问题。",
      paragraphs: [
        "第三幕结束时，a0 回答“5”，a1 回答“6”，二者的 `status` 都是 `COMPLETED`。该状态只表示 generation 以 stop 正常终止，不包含正确性判断；结果质量由 reward function 独立评价。",
        "本教学 fixture 使用确定性二元规则：response 与 label 相同则 raw reward 为 1，否则为 0。因此 a0/a1 得到 1/0，b0/b1 同样得到 1/0。reward 写回不会改变 response、tokens 或 terminal status。",
        "collect 的默认单位是候选数量完整的 prompt group，而不是单条高分 Sample。`[a0, a1]` 作为 group 0 返回，`[b0, b1]` 作为 group 1 返回；完整性指候选数满足配置，不表示组内所有 response 都正确。",
      ],
      directAnswer:
        "因为 `reward=0` 是一条评价结果，不是删除指令。默认本课路径会保留 a1，并把 a0/a1 作为完整 group 一起交给下一阶段；正是 1 与 0 的差异，让后续组内比较有东西可学。只有显式启用的过滤逻辑才可能舍弃一个 group，而且它与 reward 本身是两回事。",
      evidenceLead: "下面用 group 0 验证生成终止、逐条评价与按组收集三个步骤。",
      takeaway: "`status` 描述 generation 的终止方式；`reward` 评价结果；`collect` 决定哪些完整 group 进入本轮 rollout 结果。",
    },
    walkthrough: {
      kicker: "教学 fixture · group 0",
      title: "从 terminal status 到完整 group 返回",
      introduction: "该实例隔离三个判断：generation 是否结束、response 得分多少、group 是否满足收集条件。",
      steps: [
        {
          label: "01 · 生成已结束",
          title: "两次 generation 都正常终止",
          body: "a0 与 a1 都正常停止；此刻只知道它们说了什么，还没有评价好坏。",
          facts: [
            "a0 → response \"5\" · COMPLETED",
            "a1 → response \"6\" · COMPLETED",
            "两条 reward 都是 None",
          ],
        },
        {
          label: "02 · Reward 评价",
          title: "逐条计算二元 reward",
          body: "教学规则把正确记为 1、错误记为 0；它改变 reward，不改变生成历史。",
          facts: [
            "a0: \"5\" = label \"5\" → reward 1",
            "a1: \"6\" ≠ label \"5\" → reward 0",
            "status 仍都是 COMPLETED",
          ],
        },
        {
          label: "03 · collect 收回",
          title: "按完整 group 返回结果",
          body: "collect 保留 prompt group 边界；低分候选仍是组内比较所需的数据。",
          facts: [
            "group 0 = [a0(1), a1(0)]",
            "group 1 = [b0(1), b1(0)]",
            "本课收回 2 个完整 group",
          ],
        },
      ],
      caption: "collect 造成的是容器层面的变化：完整 group 被加入 rollout 结果 `data`；它不会在 Sample 里凭空新增一个 `collected=true` 字段。下一幕才会把这些 raw reward 转成训练侧需要的派生值。",
    },
    fieldChanges: [
      "判分写回原记录：a0/a1 的 `reward: None → 1 / 0`",
      "另一组同样判分：b0/b1 的 `reward: None → 1 / 0`",
      "生成历史保持原样：`response`、`tokens`、`loss_mask`、`status` 不被判分改写",
      "收集保留组边界：`group 0=[a0,a1]`，`group 1=[b0,b1]`",
      "collect 改变的是 rollout 结果容器，不会给 Sample 新增 `collected` 字段",
    ],
    explanation: [
      {
        id: "act-4-fact",
        kind: "source-fact",
        title: "源码路径：生成与 hooks 完成后计算 reward",
        body: "默认 `generate_and_rm` 路径先生成 Sample，再运行 sample hooks；如果 Sample 没有被 abort、也尚未自带 reward，才调用 reward function 并把结果写入 `Sample.reward`。随后 `generate_rollout_async` 等待 group 返回，检查组内候选数量，再把整个 group 加入收集结果。",
      },
      {
        id: "act-4-fixture",
        kind: "teaching-fixture",
        title: "教学配置：1/0 reward 不是线上 RM 实测",
        body: "fixture 直接固定 a0、b0 的 raw reward 为 1，a1、b1 为 0；四条都保持 `COMPLETED`。这样能先看清数据形状，但不代表真实任务只能做二元评分。生产路径可以调用规则函数、自定义 reward function 或服务；本例没有发送网络 reward 请求。",
      },
      {
        id: "act-4-preview",
        kind: "advanced-preview",
        title: "可选路径：dynamic filter 在 group 层过滤",
        body: "显式配置 dynamic filter 后，函数会看到一个完整 group，并决定整组 keep / drop；被 drop 的组不计入目标数量，收集循环会继续取新数据。它不是“reward 为 0 就删除该 Sample”的默认规则。partial 模式还可能回收 abort group，本课暂不展开恢复协议。",
      },
    ],
    sourceRefIds: ["rollout.generate-and-rm", "rollout.generate-async"],
    glossaryTermIds: ["raw-reward", "loss-mask", "terminal-status", "dynamic-filter"],
    misconception: {
      belief: "collect 只保留 reward 高的 Sample，所以 a1 与 b1 会在这一幕消失。",
      correction: "默认收集单位是完整 group，而不是单条高分答案。本课保留 a0/a1 与 b0/b1；可选 dynamic filter 也在 group 层明确做 keep / drop，不等于逐条删除零分 Sample。",
    },
    microCheck: {
      prompt: "a0 的 status=COMPLETED、reward=1；a1 的 status=COMPLETED、reward=0。这三个值分别说明什么？",
      answer: "两条生成都正常结束；a0 的结果被判为正确，a1 的结果被判为错误。它们仍属于同一个完整 group。",
      feedback: "status 讲终止方式，reward 讲结果评价；两者都不是 collect 的单条删除开关。",
    },
    transition: "两组 Sample 已携带 raw reward 返回。下一幕说明为什么它们仍需显式转换和排程，才能成为 trainer 输入。",
  },
  {
    id: "act-5",
    number: 5,
    slug: "conversion-and-schedule",
    title: "第五幕：转换与排程——从 Sample 到 per-DP train data",
    shortTitle: "转换与排程",
    durationMinutes: 4,
    drivingQuestion: "四条 Sample 已经有回答和分数，为什么还不能直接交给 Megatron？",
    stage: {
      actor: "RolloutManager",
      visual: "检查 RolloutManager 如何显式构造训练字段，并按 logical rollout 与 batch 约束生成两个 training step。",
    },
    prediction: {
      prompt: "group 0 的 raw reward 是 [1, 0]，本例只做组内中心化。转换后应保留哪两组值？",
      options: [
        { id: "raw-centered", label: "raw_reward=[1,0]，rewards=[0.5,-0.5]" },
        { id: "overwrite", label: "raw_reward=[0.5,-0.5]，rewards=[0.5,-0.5]" },
        { id: "unchanged", label: "raw_reward=[1,0]，rewards=[1,0]" },
      ],
      correctOptionId: "raw-centered",
      feedback: {
        correct: "正确。原始评价与派生训练信号必须保持不同语义。",
        incorrect: "converter 会保留 raw reward，再显式构造组内相对训练信号。",
      },
    },
    narrative: {
      kicker: "训练输入边界 · 数据转换与 schedule",
      title: "RolloutManager 将生成记录转换为 trainer 的显式输入。",
      paragraphs: [
        "第四幕返回的四条 Sample 保存语义输入、生成历史与 raw reward，适合追踪单次 rollout。Megatron actor 不直接读取这些 Python dataclass；它接收的是字段对齐、身份明确并按 DP rank 打包的 train data。",
        "转换首先区分原始评价与派生训练信号。`[1,0,1,0]` 被保留为 `raw_reward`；两组分别减去均值 0.5，得到 `rewards=[+0.5,-0.5,+0.5,-0.5]`。本 fixture 关闭标准差归一化，因此这里只进行组内中心化。",
        "converter 随后构造 `sample_indices`、`rollout_ids`、`loss_masks` 等字段。scheduler 再按照 logical rollout、`global_batch_size=2` 与 DP 约束生成两个 training step：step 0 包含 a0/a1，step 1 包含 b0/b1。转换定义字段语义，排程定义消费顺序；二者是不同边界。",
      ],
      directAnswer:
        "因为 Sample 是生成侧的历史记录，而 trainer 需要显式构造、按 DP rank 打包并带有 schedule 的 train data。raw reward、派生 reward、身份、mask 与 batch 计划都必须通过 converter 和 scheduler 明确定义；它们不会自动从 Sample 出现在 Megatron 输入中。",
      evidenceLead: "下面将原始 Sample、字段转换和 schedule 构造分开验证。",
      takeaway: "Sample 保存 rollout 历史；train data 定义这些记录如何参与训练。",
    },
    walkthrough: {
      kicker: "教学 fixture · 4 个 logical rollout",
      title: "从四条 Sample 到两个 training step",
      introduction: "实例依次展示原始记录、派生训练字段和最终 schedule。",
      steps: [
        {
          label: "01 · 收到 Sample",
          title: "输入保留两组生成历史",
          body: "四条 Sample 保存 response、terminal status 与 raw reward，并维持原有 group 关系。",
          facts: [
            "group 0 → a0(1), a1(0)",
            "group 1 → b0(1), b1(0)",
            "共 4 条 physical Sample",
          ],
        },
        {
          label: "02 · 转成 train_data",
          title: "显式构造训练字段",
          body: "converter 保留原分，同时计算组内相对信号，并把身份与 mask 排成等长数组。",
          facts: [
            "raw_reward = [1, 0, 1, 0]",
            "rewards = [+0.5, -0.5, +0.5, -0.5]",
            "sample_indices = [0, 1, 2, 3]",
            "rollout_ids = [0, 1, 2, 3]",
          ],
        },
        {
          label: "03 · 构造 schedule",
          title: "构造两个 training step",
          body: "每个 step 容纳 2 个 logical rollout；本 fixture 没有裁掉任何记录。",
          facts: [
            "step 0 → a0, a1 · rollout 0, 1",
            "step 1 → b0, b1 · rollout 2, 3",
            "used = 4 · trimmed = 0",
          ],
        },
      ],
      caption: "`raw_reward` 与 `rewards` 不是重复字段：前者保留原始判分，后者是本课的组内中心化训练信号。`group_index` 表示谁一起比较，`rollout_id` 则守住一次 logical rollout 在训练排程里的身份。",
    },
    fieldChanges: [
      "原始判分被保留：`reward=[1,0,1,0] → raw_reward=[1,0,1,0]`",
      "训练信号被派生：两组分别减去均值 0.5，得到 `rewards=[+0.5,-0.5,+0.5,-0.5]`",
      "记录身份显式成列：`index → sample_indices=[0,1,2,3]`",
      "本例缺失的逻辑身份只在 train data 中补齐：`rollout_ids=[0,1,2,3]`",
      "response 侧 mask 被打包：`loss_masks=[[1],[1],[1],[1]]`，`rollout_mask_sums=[1,1,1,1]`",
      "排程守恒：`4 logical rollouts ÷ global_batch_size 2 = 2 training steps`",
    ],
    explanation: [
      {
        id: "act-5-fact",
        kind: "source-fact",
        title: "源码边界：字段转换与 DP 排程分离",
        body: "RolloutManager 先校验 rollout 身份并 flatten 生成结果，随后 `_post_process_rewards` 计算 raw 与派生 reward，`_convert_samples_to_train_data` 显式组装训练字段，最后 `_split_train_data_by_dp` 调用 scheduler 按 logical rollout 与 batch 约束分配到 DP rank。trainer 只收到这份打包结果。",
      },
      {
        id: "act-5-fixture",
        kind: "teaching-fixture",
        title: "教学配置：两个 step 的推导",
        body: "本例有 4 个 logical rollout，`global_batch_size=2`、`dp_size=1`、`micro_batch_size=2`，因此确定性排程给出两个 step：a0/a1 与 b0/b1。`raw_samples_frozen` 是播放器用来区分历史层与派生层的教学状态；它不是对所有生产 converter 都作“永不修改 Sample”的额外承诺。",
      },
      {
        id: "act-5-preview",
        kind: "advanced-preview",
        title: "扩展边界：fan-out 必须保持 rollout_id",
        body: "一次 logical rollout fan-out 成多个物理训练片段时，兄弟片段拥有不同 `index`，却必须共享同一个 `rollout_id`；scheduler 据此把它们放在同一 training step，并让 loss reducer 按一次 logical rollout 计数。本 fixture 没有启用 fan-out，所以四条 Sample 各自对应一个 rollout id。",
      },
    ],
    sourceRefIds: [
      "rollout.manager-generate",
      "rollout.get-data",
      "rollout.post-process-rewards",
      "rollout.convert-train-data",
      "rollout.split-train-data",
      "schedule.build-dp-schedule",
      "test.dp-schedule-contract",
    ],
    glossaryTermIds: [
      "logical-rollout",
      "rollout-id",
      "centered-reward",
      "train-data",
      "rollout-batch",
      "training-step",
    ],
    misconception: {
      belief: "Sample 已经带着 reward 和 mask，Megatron 直接读取这四个对象就能训练。",
      correction: "Megatron actor 不接收 Sample dataclass；训练字段必须经过 converter 显式映射，再由 scheduler 和 per-rank packaging 交付。Sample 字段不会跨过边界后自动出现。",
    },
    microCheck: {
      prompt: "group 0 的 raw reward 是 [1,0]，均值为 0.5；关闭 std normalization 后，raw_reward 与 rewards 分别是什么？",
      answer: "raw_reward 仍是 [1,0]；rewards 是 [0.5,-0.5]。",
      feedback: "`raw_reward` 保留原始评价，`rewards` 表达组内相对训练信号；二者语义不同。",
    },
    transition: "per-DP train data 与 schedule 已经构造完成。下一幕检查 Megatron 消费什么数据、更新什么状态，以及哪些历史信息保持不变。",
  },
  {
    id: "act-6",
    number: 6,
    slug: "training",
    title: "第六幕：训练——消费 train data 并更新 actor 参数",
    shortTitle: "训练",
    durationMinutes: 2.5,
    drivingQuestion: "Megatron 究竟读了什么、改变了什么，又为什么没有改写那四条 Sample？",
    stage: {
      actor: "Megatron actor",
      visual: "两个 training step 由 Megatron 依次消费；训练侧参数更新为 actor@1，SGLang 与历史 Sample 暂时保持 actor@0。",
    },
    prediction: {
      prompt: "train 刚完成、weight sync 还没开始。Megatron、SGLang 与历史 Sample 分别应记录哪个版本？",
      options: [
        { id: "split", label: "Megatron=actor@1；SGLang=actor@0；历史 Sample=actor@0" },
        { id: "all-new", label: "三者都立刻变成 actor@1" },
        { id: "all-old", label: "三者都保持 actor@0，直到下一轮训练" },
      ],
      correctOptionId: "split",
      feedback: {
        correct: "正确。训练侧、生成侧与历史记录是三个独立状态。",
        incorrect: "optimizer 只改变训练侧参数；发布和历史可追溯性属于另外两个边界。",
      },
    },
    narrative: {
      kicker: "优化边界 · 参数状态与历史状态",
      title: "Megatron 更新训练侧参数，不改写历史 Sample。",
      paragraphs: [
        "Megatron 接收 RolloutManager 构造的 per-DP train data，其中 token、response 长度、派生 reward、loss mask 与 schedule 已经对齐。本 fixture 只有一个 DP rank：step 0 包含 a0/a1，step 1 包含 b0/b1。训练函数不需要重新读取 Sample 或推断 group 关系。",
        "具体算法配置决定 log-prob、advantage / returns 与 loss 的构造方式。跨算法不变的边界是：reward 提供优化信号，`loss_mask` 决定 response 中哪些位置可以贡献训练目标。本例四条 mask 均为 `[1]`；mask 为 0 的位置可以存在于 batch 中，但不会以相同方式贡献 policy loss。",
        "两个 training step 完成后，optimizer 更新训练侧模型参数。教学播放器将版本变化记为 `actor@0 → actor@1`。历史 Sample 的 `weight_versions=[actor@0]` 保持不变，因为它记录生成时的 policy；此刻 `weights_published=false`，说明 rollout engine 尚未获得新参数。",
      ],
      directAnswer:
        "Megatron 消费 converter 与 scheduler 交付的 per-DP train data，并据此更新 actor 参数；它不消费 Sample dataclass，也不会把 optimizer 的结果写回历史 Sample。训练结束只证明训练侧已有 actor@1，不等于 rollout engine 已经使用 actor@1。",
      evidenceLead: "下面分别检查训练输入、参数状态和历史 Sample，避免混淆三个对象。",
      takeaway: "optimizer 更新当前 actor 参数；历史 Sample 继续记录生成它时使用的 policy。",
    },
    walkthrough: {
      kicker: "教学 fixture · 两个 training step",
      title: "训练输入、参数状态与历史状态",
      introduction: "实例分别展示 Megatron 的输入、optimizer 的输出以及历史 Sample 的不变量。",
      steps: [
        {
          label: "01 · 接收 per-DP 数据",
          title: "trainer 接收既定 schedule",
          body: "DP rank 0 收到两步计划；每一步拿到 2 个 logical rollout 及其训练字段。",
          facts: [
            "step 0 → a0, a1",
            "step 1 → b0, b1",
            "global batch = 2 · micro batch = 2",
          ],
        },
        {
          label: "02 · 计算并训练",
          title: "按配置构造并应用训练目标",
          body: "算法按配置准备训练信号，再对计划中的两个 step 执行 actor training。",
          facts: [
            "rewards → +0.5, -0.5, +0.5, -0.5",
            "loss_masks → [1], [1], [1], [1]",
            "train(...) 执行 schedule",
          ],
        },
        {
          label: "03 · 训练完成",
          title: "训练侧参数更新为 actor@1",
          body: "版本变化只发生在训练侧；生成侧与历史记录暂时保持 actor@0。",
          facts: [
            "Megatron actor → actor@1",
            "SGLang rollout → actor@0",
            "weights_published = false",
            "历史 Sample → actor@0",
          ],
        },
      ],
      caption: "此时存在三个相互独立的状态：历史 Sample 记录 actor@0，train data 描述训练输入，actor state 已更新为 actor@1。它们不是同一个对象，也不应被同步改写。",
    },
    fieldChanges: [
      "训练输入跨过设备边界：per-DP `tokens`、`loss_masks` 等字段被搬到执行设备",
      "既定排程被消费：step 0 读取 a0/a1，step 1 读取 b0/b1",
      "训练信号按配置准备：log-prob、advantage / returns 与 loss 进入 actor training",
      "模型参数发生变化：Megatron `actor@0 → actor@1`",
      "发布状态尚未变化：`weights_published=false`，SGLang 仍是 `actor@0`",
      "历史层保持原样：四条 `Sample.weight_versions` 仍记录 `actor@0`",
    ],
    explanation: [
      {
        id: "act-6-fact",
        kind: "source-fact",
        title: "源码路径：从 per-DP 数据到 actor training",
        body: "`MegatronTrainRayActor._get_rollout_data` 取回 per-DP 数据，把 token、loss mask 等训练字段搬到执行设备；`train_actor` 再按配置准备 log-prob 与 advantage / returns，最后把 data iterator、microbatch 数和 global batch size 交给 `train(...)`。这条调用链没有重新读取 Sample dataclass。",
      },
      {
        id: "act-6-fixture",
        kind: "teaching-fixture",
        title: "教学范围：actor@1 仅表示参数版本边界",
        body: "播放器用 `actor@0 → actor@1` 表示这轮训练前后的参数版本，并把两个已排定的 training step 合并成一次可读事件。它不模拟真实 tensor 值、loss 曲线、optimizer 内部状态、GPU 吞吐或训练耗时，也不把 actor@1 当作生产 checkpoint 名。",
      },
      {
        id: "act-6-preview",
        kind: "advanced-preview",
        title: "算法范围：不同目标共享相同训练输入边界",
        body: "PPO、GRPO、GSPO 与 CISPO 会以不同方式构造 advantage、校正概率并定义 loss；有些配置还会引入 ref、critic、teacher 或 routing replay。本幕不把它们揉成一个公式，只保留共同边界：训练函数收到显式 train data，mask 控制有效位置，optimizer 更新 actor。",
      },
    ],
    sourceRefIds: ["actor.consume-rollout-data", "actor.train"],
    glossaryTermIds: ["train-data", "training-step", "loss-mask", "weight-version"],
    misconception: {
      belief: "actor 训练到 actor@1 后，a0/a1 这些 Sample 也应该把 weight_versions 改成 actor@1。",
      correction: "不能改。`weight_versions` 记录回答生成时使用的 policy；训练改变的是当前 actor 参数。若把历史 Sample 改成 actor@1，反而会抹掉 off-policy 与可追溯信息。",
    },
    microCheck: {
      prompt: "`trained` 事件刚发生、weight sync 还没开始：Megatron、SGLang 与历史 Sample 分别记录哪个版本？",
      answer: "Megatron 是 actor@1；SGLang 仍是 actor@0；历史 Sample 也仍记录 actor@0。",
      feedback: "训练侧版本、生成侧版本与历史版本可以暂时不同；这正是下一幕必须存在的理由。",
    },
    transition: "训练侧已经得到 actor@1，但 rollout engine 仍持有 actor@0。最后一幕分析显式权重发布与请求一致性。",
  },
  {
    id: "act-7",
    number: 7,
    slug: "weight-return",
    title: "第七幕：权重发布——使 actor@1 对后续 rollout 可见",
    shortTitle: "权重发布",
    durationMinutes: 2.5,
    drivingQuestion: "训练侧已经有 actor@1，为什么 SGLang 不会自动、也不能在请求中途换上它？",
    stage: {
      actor: "Weight sync",
      visual: "训练侧已是 actor@1，SGLang 仍持有 actor@0；只有显式发布完成后启动的 generation 才能使用新版本。",
    },
    prediction: {
      prompt: "一条 generation 在 actor@1 发布前已经开始。发布发生时，这条请求应怎样处理版本？",
      options: [
        { id: "finish-old", label: "先用 actor@0 完成；发布后启动的新请求再使用 actor@1" },
        { id: "switch-midway", label: "在 response 中途无条件切换到 actor@1" },
        { id: "rewrite-history", label: "完成后把它的历史版本改写为 actor@1" },
      ],
      correctOptionId: "finish-old",
      feedback: {
        correct: "正确。发布协调 in-flight generation，避免单次请求中途混用版本。",
        incorrect: "判断一条 Sample 的版本，要看 generation 启动时 rollout engine 持有哪一版。",
      },
    },
    narrative: {
      kicker: "分布式状态边界 · 训练完成与发布完成",
      title: "训练完成和 rollout 可用是两个不同的系统事件。",
      paragraphs: [
        "第六幕结束时，Megatron 已经持有 `actor@1`，而 SGLang rollout engine 仍服务于 `actor@0`。两个版本同时存在是预期状态：trainer 与 generation engine 是独立的参数持有者，optimizer step 只更新前者。",
        "主循环因此必须显式调用 `update_weights`。weight updater 连接可更新的 rollout engines，传输新参数并等待发布边界完成。成功后，生成侧版本才从 actor@0 切换到 actor@1，`weights_published` 变为 true；历史 Sample 不被修改。",
        "同步路径遵循 generate → train → update weights → next generation。异步路径可以使 rollout(i+1) 与 train(i) 重叠，因此已启动的 generation 仍可能使用 actor@i。发布前必须协调 in-flight generation，避免单次请求在执行过程中混用不同参数版本。",
      ],
      directAnswer:
        "因为 trainer 与 SGLang 是不同的权重持有者，optimizer step 只更新 trainer。新参数必须经过显式 `update_weights` 才会成为 rollout engine 的可用版本；异步模式还要先协调正在生成的请求。只有发布边界完成之后启动的新一轮 generation，才能被本课安全地记作 actor@1。",
      evidenceLead: "下面分别检查训练侧版本、生成侧版本和发布后新请求的版本。",
      takeaway: "训练产生新参数；weight sync 使新参数对后续 generation 可见。二者之间是显式一致性边界。",
    },
    walkthrough: {
      kicker: "教学 fixture · 参数发布状态",
      title: "actor@1 何时对新 generation 生效",
      introduction: "实例依次比较训练完成、权重发布和下一轮 generation 三个状态。",
      steps: [
        {
          label: "01 · 训练刚结束",
          title: "新旧版本同时存在",
          body: "新参数只在 Megatron 一侧；SGLang 仍用旧版本响应生成请求。",
          facts: [
            "Megatron → actor@1",
            "SGLang → actor@0",
            "weights_published = false",
          ],
        },
        {
          label: "02 · 显式发布",
          title: "update_weights 执行显式发布",
          body: "weight updater 把训练侧的新参数交给 rollout engines；完成后才切换生成版本。",
          facts: [
            "actor_model.update_weights()",
            "SGLang → actor@1",
            "weights_published = true",
          ],
        },
        {
          label: "03 · 下一轮开始",
          title: "发布后的新 Sample 记录 actor@1",
          body: "闭环回到 DataSource；随后启动的 generation 使用已发布版本，旧记录继续保存旧事实。",
          facts: [
            "next_cycle_ready = true",
            "new Sample → actor@1",
            "a0/a1/b0/b1 → 仍是 actor@0",
          ],
        },
      ],
      caption: "`actor@0` 与 `actor@1` 是教学版本标签，不是 checkpoint 文件名；页面也不模拟具体 transport。无论权重怎样传输，`train 完成 ≠ rollout 已发布` 这条边界都必须成立。",
    },
    fieldChanges: [
      "发布前的版本分叉：Megatron 为 `actor@1`，SGLang 仍为 `actor@0`",
      "显式调用更新边界：`actor_model.update_weights()`",
      "发布完成后生成侧切换：`rollout_version: actor@0 → actor@1`",
      "系统确认新版本可用：`weights_published: false → true`",
      "历史记录保持不变：a0/a1/b0/b1 的 `weight_versions=[actor@0]`",
      "闭环重新起跑：下一轮新 Sample 才会记录 `actor@1`",
    ],
    explanation: [
      {
        id: "act-7-fact",
        kind: "source-fact",
        title: "源码边界：主循环显式调用 update_weights",
        body: "同步 `train` 主循环先等待当前 actor training 完成，再调用 `actor_model.update_weights()`，之后才进入下一次 generation。`MegatronTrainRayActor.update_weights` 连接可更新的 SGLang engines，并由 weight updater 执行参数发布；这条路径改变 engine 持有的权重，不会遍历并重写旧 Sample。",
      },
      {
        id: "act-7-fixture",
        kind: "teaching-fixture",
        title: "教学范围：版本标签不是网络传输 trace",
        body: "`actor@0/actor@1`、`weights_published` 与时间块用于固定表达版本和先后关系，不是 checkpoint 名、网络 trace 或性能 benchmark。事件 `weights_synced` 把 SGLang 切到 actor@1；随后 `next_cycle_ready` 只说明下一轮可以开始，不会修改上一轮四条 Sample。",
      },
      {
        id: "act-7-preview",
        kind: "advanced-preview",
        title: "异步边界：重叠执行不取消发布一致性",
        body: "async 会提前启动 rollout(i+1)，让它与 train(i) 重叠；因此这批 generation 可能仍由 actor@i 完成。到达配置的更新间隔时，主循环先等待那个 in-flight generation，再调用 update weights，防止参数在一次 generation 中途切换。异步改变重叠关系，不取消发布一致性。",
      },
    ],
    sourceRefIds: ["loop.sync", "loop.async", "actor.update-weights"],
    glossaryTermIds: ["weight-version", "weight-sync", "asynchronous-rollout"],
    misconception: {
      belief: "Megatron 出现 actor@1 的那一刻，SGLang 和所有已经开始的请求也会自动切成 actor@1。",
      correction: "不会。SGLang 要等显式 weight sync；已经开始的异步 generation 还会先完成，发布才发生。这样一条请求不会在半途混用两版权重。",
    },
    microCheck: {
      prompt: "训练结束后立刻启动一条新 generation，但 weight sync 尚未完成；它应该记录 actor@0 还是 actor@1？",
      answer: "仍应记录 actor@0，因为 rollout engine 还没有完成 actor@1 的发布。只有同步完成后启动的新一轮才能记录 actor@1。",
      feedback: "判断版本不要看 trainer 何时训练完，要看 generation 启动时 rollout engine 已发布哪一版。",
    },
    transition: "发布完成后启动的新 generation 可以使用 actor@1；上一轮 Sample 继续保留 actor@0 的生成历史。至此，训练闭环的状态边界完整闭合。",
  },
];

export const sampleJourneyAssessment = {
  id: "core.sample-journey.check",
  version: 2,
  title: "章末知识检查",
  description: "可无限重试。至少答对 8 题，并且四道关键边界题必须正确。",
  questions: [
    {
      id: "q1",
      type: "ordering",
      prompt: "把一条 Sample 的七段闭环按发生顺序排列。",
      options: [
        { id: "dataset", label: "Dataset 构造初始 Sample" },
        { id: "group", label: "DataSource 建立同组候选" },
        { id: "generate", label: "SGLang 生成 response" },
        { id: "reward", label: "Reward 逐条评分，collect 按组收回" },
        { id: "convert", label: "RolloutManager 转换与排程" },
        { id: "train", label: "Megatron actor 训练" },
        { id: "sync", label: "weight sync 发布新权重" },
      ],
      correctOrder: ["dataset", "group", "generate", "reward", "convert", "train", "sync"],
      required: false,
      answerSummary: "Dataset → 分组 → 生成 → Reward 评分 → collect 按组收回 → 转换/排程 → train → weight sync。",
      feedback: {
        correct: "顺序正确。你已经能复原闭环骨架。",
        incorrect: "先只追踪交接关系，不要把字段细节混进顺序。回看 90 秒闭环。",
      },
      returnTo: { label: "回看 90 秒闭环", href: "/learn/sample-journey#overview" },
    },
    {
      id: "q2",
      type: "multiple",
      prompt: "关于刚由 Dataset 构造出的初始 Sample，哪些说法正确？",
      options: [
        { id: "semantic", label: "已经有 prompt、label 与 metadata" },
        { id: "pending", label: "status 为 PENDING" },
        { id: "empty", label: "tokens 与 response 仍为空" },
        { id: "rewarded", label: "已经有组内中心化 reward" },
        { id: "tensor", label: "已经是 Megatron tensor batch" },
      ],
      correctOptionIds: ["semantic", "pending", "empty"],
      required: false,
      answerSummary: "初始 Sample 保存语义输入，生成与训练侧字段仍未准备。",
      feedback: {
        correct: "正确。Sample 已构造，但还没有经过生成、评价与训练数据转换。",
        incorrect: "注意时间点：Dataset 只完成了 Sample 的初始语义字段。",
      },
      returnTo: { label: "回到第一幕", href: "/learn/sample-journey#act-1", actId: "act-1" },
    },
    {
      id: "q3",
      type: "single",
      prompt: "3 个 prompts、每个 prompt 生成 N=4 个同组候选，会得到多少 group 与物理 Sample？",
      options: [
        { id: "3-12", label: "3 个 group，12 条 Sample" },
        { id: "12-12", label: "12 个 group，12 条 Sample" },
        { id: "3-4", label: "3 个 group，4 条 Sample" },
        { id: "4-12", label: "4 个 group，12 条 Sample" },
      ],
      correctOptionIds: ["3-12"],
      required: false,
      answerSummary: "prompt 数决定 group 数；每组 N 个候选，所以 3×4=12 条 Sample。",
      feedback: {
        correct: "正确。同组 group_index 相同，但物理 index 各不相同。",
        incorrect: "不要把候选数当成 group 数：一个 prompt 对应一个 group。",
      },
      returnTo: { label: "回到第二幕", href: "/learn/sample-journey#act-2", actId: "act-2" },
    },
    {
      id: "q4",
      type: "single",
      prompt: "prompt 有 6 个 token、response 有 4 个 token。哪组长度关系正确？",
      options: [
        { id: "10-4-4", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=4" },
        { id: "10-10-4", label: "len(tokens)=10，response_length=10，len(rollout_log_probs)=4" },
        { id: "6-4-10", label: "len(tokens)=6，response_length=4，len(rollout_log_probs)=10" },
        { id: "10-4-10", label: "len(tokens)=10，response_length=4，len(rollout_log_probs)=10" },
      ],
      correctOptionIds: ["10-4-4"],
      required: true,
      answerSummary: "tokens 包含 prompt 前缀和 response 后缀；response 元数据只在 response 空间对齐。",
      feedback: {
        correct: "关键不变量正确。",
        incorrect: "这是一道必对题：把完整 tokens 与 response-side 元数据分开计算。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q5",
      type: "single",
      prompt: "response 依次包含 2 个模型 token、2 个工具 token、3 个模型 token。正确 mask 与有效长度是什么？",
      options: [
        { id: "mask-correct", label: "[1,1,0,0,1,1,1]，有效长度 5" },
        { id: "mask-all", label: "[1,1,1,1,1,1,1]，有效长度 7" },
        { id: "mask-tool", label: "[0,0,1,1,0,0,0]，有效长度 2" },
        { id: "mask-short", label: "[1,1,1,1,1]，有效长度 5" },
      ],
      correctOptionIds: ["mask-correct"],
      required: true,
      answerSummary: "模型动作位置为 1，工具 observation 位置为 0；mask 仍与全部 response 位置等长。",
      feedback: {
        correct: "关键 mask 对齐正确。",
        incorrect: "这是一道必对题：工具 token 仍占 response 位置，但不贡献训练 mask。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q6",
      type: "single",
      prompt: "finish reason 与 terminal status 的正确映射是哪一项？",
      options: [
        { id: "correct", label: "stop→COMPLETED，length→TRUNCATED，abort→ABORTED" },
        { id: "swap", label: "stop→TRUNCATED，length→COMPLETED，abort→ABORTED" },
        { id: "all", label: "三者都映射为 COMPLETED" },
        { id: "pending", label: "三者都保持 PENDING" },
      ],
      correctOptionIds: ["correct"],
      required: false,
      answerSummary: "stop、length、abort 分别映射为 COMPLETED、TRUNCATED、ABORTED。",
      feedback: {
        correct: "正确。status 描述生成如何结束。",
        incorrect: "回看生成终止阶段，不要把 reward 与 terminal status 混淆。",
      },
      returnTo: { label: "回到第三幕", href: "/learn/sample-journey#act-3", actId: "act-3" },
    },
    {
      id: "q7",
      type: "multiple",
      prompt: "下面哪些值不是 raw Sample 字段，而是在转换后才出现的 derived train data？",
      options: [
        { id: "centered", label: "组内中心化 reward" },
        { id: "mask-sum", label: "rollout_mask_sums" },
        { id: "status", label: "terminal status" },
        { id: "prompt", label: "prompt" },
      ],
      correctOptionIds: ["centered", "mask-sum"],
      required: false,
      answerSummary: "组内中心化 reward 与 rollout_mask_sums 都在 Sample→train data 边界派生。",
      feedback: {
        correct: "正确。你没有把派生训练数据伪装成 Sample 字段。",
        incorrect: "锁定 raw Sample 与 derived train data 两栏，再看字段从哪里出现。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q8",
      type: "single",
      prompt: "一次逻辑 rollout fan-out 成多个训练片段时，为什么它们共享 rollout_id、却拥有不同 index？",
      options: [
        {
          id: "identity-correct",
          label: "rollout_id 标记同一逻辑执行，index 标记各物理 Sample，避免重复计数又保留独立身份",
        },
        { id: "duplicate", label: "它们其实是完全相同的重复对象，所以两个 ID 都应该相同" },
        { id: "group", label: "rollout_id 等同于 prompt group 的 group_index" },
        { id: "random", label: "两种 ID 都只是随机展示值，下游不使用" },
      ],
      correctOptionIds: ["identity-correct"],
      required: true,
      answerSummary: "rollout_id 聚合逻辑执行；index 保持每个物理训练片段的唯一身份。",
      feedback: {
        correct: "关键身份边界正确。",
        incorrect: "这是一道必对题：不要把 prompt group、逻辑 rollout 与物理 Sample 合并。",
      },
      returnTo: { label: "回到第五幕", href: "/learn/sample-journey#act-5", actId: "act-5" },
    },
    {
      id: "q9",
      type: "single",
      prompt: "异步路径中的 rollout(i+1) 为什么可能仍使用 actor@i？",
      options: [
        { id: "overlap", label: "它与 train(i) 重叠并在新权重发布前开始；发布前会等待进行中的 generation" },
        { id: "rewrite", label: "新权重会在完成后回写历史 Sample，所以版本无所谓" },
        { id: "no-sync", label: "异步路径永远不做 weight sync" },
        { id: "mid-request", label: "请求进行到一半时会无条件切到 actor@i+1" },
      ],
      correctOptionIds: ["overlap"],
      required: false,
      answerSummary: "生成与训练可以重叠，但显式发布边界仍要等待进行中的 generation，避免请求中途混用版本。",
      feedback: {
        correct: "正确。异步改变时间重叠，不取消版本边界。",
        incorrect: "对照 sync/async 时间线，找到 generation、train 与 weight barrier 的相对位置。",
      },
      returnTo: { label: "回到第七幕", href: "/learn/sample-journey#act-7", actId: "act-7" },
    },
    {
      id: "q10",
      type: "multiple",
      prompt: "综合调试记录如下：a0/a1 都是 COMPLETED，reward 分别为 1/0；collect 只返回 a0；训练后 Megatron 已是 actor@1，而 SGLang 仍是 actor@0；系统又把历史 a0 的 weight_versions 改成 actor@1。哪些现象首先违反了本课的默认边界？",
      options: [
        { id: "incomplete-group", label: "collect 因 reward=0 丢掉 a1，使默认收集结果不再是完整 group" },
        { id: "version-split", label: "weight sync 前 Megatron 与 SGLang 暂时持有不同版本" },
        { id: "history-rewrite", label: "把历史 a0 的生成版本从 actor@0 改写为 actor@1" },
        { id: "completed-zero", label: "a1 同时具有 status=COMPLETED 与 reward=0" },
      ],
      correctOptionIds: ["incomplete-group", "history-rewrite"],
      required: true,
      answerSummary: "默认 collect 保留完整 group；历史 Sample 必须保留生成时的 policy 版本。训练侧与生成侧在发布前暂时分叉，以及 COMPLETED 与零 reward 并不矛盾。",
      feedback: {
        correct: "正确。你能区分真正的边界破坏与正常的暂态分叉。",
        incorrect: "逐项问四个问题：generation 是否正常结束、reward 是否只是评价、collect 是否保持完整 group、历史版本是否仍可追溯。",
      },
      returnTo: { label: "回看评价、训练与发布边界", href: "/learn/sample-journey#act-4", actId: "act-4" },
    },
  ] satisfies AssessmentQuestion[],
  completion: {
    minCorrect: 8,
    requiredQuestionIds: ["q4", "q5", "q8", "q10"],
    requiredActIds: ["act-1", "act-2", "act-3", "act-4", "act-5", "act-6", "act-7"],
    unlimitedRetries: true,
    progressScope: "device-local",
  },
} as const;

export const sampleJourneyLesson = {
  metadata: {
    schemaVersion: 1,
    id: "core.sample-journey",
    kind: "lesson",
    locale: "zh-CN",
    route: "/learn/sample-journey",
    title: "一条 Sample 的状态演化",
    summary:
      "本课沿同一条 Sample 检查七个系统边界：初始构造、候选分组、模型生成、reward 与 collect、训练数据转换、actor 更新，以及面向后续 rollout 的权重发布。",
    audiences: ["researcher", "engineer"],
    level: "slime-intro",
    duration: { minMinutes: 25, maxMinutes: 30, includesAssessment: true },
    studyModes: {
      core: { label: "核心阅读", duration: "25–30 分钟", includes: "结论、状态变化、实例与检查" },
      research: { label: "完整研究", duration: "约 60 分钟", includes: "核心阅读、源码证据、fixture、进阶边界与实验工具" },
    },
    workflowStatus: "ready",
    freshnessStatus: "current",
    visibility: "public",
    lessonRevision: 7,
    prerequisites: ["concept.rl-loop-basics"],
    learningObjectives: [
      "按顺序复述 Dataset → DataSource → SGLang → Reward → collect → train data → Megatron → weight sync 闭环。",
      "区分 dataset row、prompt group、物理 Sample、逻辑 rollout、rollout batch 与 training step。",
      "解释 tokens、response_length、loss_mask、rollout_log_probs、reward 与 status 的边界。",
      "检查 response 侧长度、逻辑身份与 batch 守恒三个关键不变量。",
      "指出 optimizer step 与权重发布的边界，并对比同步与异步的最小差异。",
    ],
    learningObjectiveIds: [
      "sample-lifecycle",
      "token-alignment",
      "identity-boundaries",
      "batch-conservation",
      "weight-publication-boundary",
    ],
    completion: {
      assessmentId: "core.sample-journey.check",
      assessmentVersion: 2,
      minCorrect: 8,
      requiredQuestionIds: ["q4", "q5", "q8", "q10"],
      requiredActs: [1, 2, 3, 4, 5, 6, 7],
    },
    baseline: {
      repository: "THUDM/slime",
      nearestTag: "v0.3.1",
      describe: "v0.3.1-1-g06ffdbe2",
      commit: "06ffdbe22be068b52f9ed0fc318c473f7030197e",
    },
    fixtureIds: ["math-2x2-v1"],
    glossaryTermIds: [
      "dataset-row",
      "sample-object",
      "prompt-group",
      "group-index",
      "sample-index",
      "logical-rollout",
      "rollout-id",
      "rollout-batch",
      "training-step",
      "response-length",
      "loss-mask",
      "rollout-log-prob",
      "raw-reward",
      "dynamic-filter",
      "centered-reward",
      "train-data",
      "terminal-status",
      "weight-version",
      "weight-sync",
      "asynchronous-rollout",
    ],
    sourceRefIds: [
      "sample.dataclass",
      "dataset.construct-sample",
      "rollout.datasource-get-samples",
      "sample.append-response-tokens",
      "rollout.convert-train-data",
      "schedule.build-dp-schedule",
      "actor.train",
      "actor.update-weights",
    ],
    testRefIds: ["test.sample-contract", "test.dp-schedule-contract"],
    owners: {
      content: "project-initiator",
      technicalReview: "project-initiator-or-designated-slime-reviewer",
    },
  },
  opening: {
    eyebrow: "阅读方法 · 跟踪同一对象",
    title: "本课只跟踪一个对象：Sample。",
    paragraphs: [
      "初始 Sample 只保存语义输入，没有 response、reward 或训练信号。后续每个组件都在明确的边界上读取已有状态、写入新字段或构造新的数据表示。",
      "DataSource 建立同组独立候选，SGLang 写回生成结果，reward function 评价 response，RolloutManager 构造 train data 与 schedule，Megatron 更新 actor 参数。",
      "训练完成并不等于生成侧已经使用新参数。最后一步必须显式发布权重；只有发布后启动的 generation 才能使用新的 actor 版本。",
    ],
    closing: "阅读策略：每一幕只回答当前组件改变了什么，以及哪些状态保持不变。",
    coverKicker: "课程模型 / 单一观察对象",
    coverCaption: "从语义输入到权重发布。",
    overviewKicker: "90 秒 · 完整因果链",
  },
  hook: {
    question: "同样答对，为什么一个 Sample 完全不学习？",
    sampleA: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[1])',
    sampleB: 'Sample(response="5", response_length=1, reward=1.0, loss_mask=[0])',
    resolution:
      "reward 评价结果；loss_mask 决定 response 中哪些 token 能参与优化。B 没有有效训练 token。",
    revealAfterActId: "act-5",
  },
  invariants: [
    "tokens = prompt token 前缀 + response token 后缀",
    "loss_mask 存在时：len(loss_mask) == response_length",
    "rollout_log_probs 存在时：len(rollout_log_probs) == response_length",
    "一次逻辑 rollout 的派生片段共享 Sample.rollout_id；每个物理 Sample 的 index 仍不同",
  ],
  overview90s: sampleJourneyOverview,
  acts: sampleJourneyActs,
  assessment: sampleJourneyAssessment,
  closingMemory:
    "Sample 记录模型在某个 policy 版本下做了什么；train data 规定 trainer 怎样聚合它；weight sync 决定下一条 Sample 由哪个 policy 产生。",
  scopeNotice: {
    sourceFact: "带“源码事实”的结论已对照固定 commit 06ffdbe2。",
    teachingFixture: "带“教学 fixture”的数值只用于稳定讲解，不是实测 trace 或性能 benchmark。",
    advancedPreview: "带“进阶预告”的内容只标出下一步，不作为本课完成要求。",
  },
} as const;
